package gateway.EAI.yongyou;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.2.7
 * Thu Jun 17 16:49:59 CST 2010
 * Generated source version: 2.2.7
 * 
 */
 
@WebService(targetNamespace = "http://xmlns.oracle.com/QueryFinanceBalanceFromYY", name = "QueryFinanceBalanceFromYY")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QueryFinanceBalanceFromYY {

    @WebResult(name = "QueryFinanceBalanceFromYYProcessResponse", targetNamespace = "http://xmlns.oracle.com/QueryFinanceBalanceFromYY", partName = "payload")
    @WebMethod(action = "process")
    public QueryFinanceBalanceFromYYProcessResponse process(
        @WebParam(partName = "payload", name = "QueryFinanceBalanceFromYYProcessRequest", targetNamespace = "http://xmlns.oracle.com/QueryFinanceBalanceFromYY")
        QueryFinanceBalanceFromYYProcessRequest payload
    );
}
