package haier.repository.dao;

import haier.repository.model.CpSequence;
import haier.repository.model.CpSequenceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CpSequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Fri Jul 22 12:56:32 CST 2011
     */
    int countByExample(CpSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Fri Jul 22 12:56:32 CST 2011
     */
    int deleteByExample(CpSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Fri Jul 22 12:56:32 CST 2011
     */
    int insert(CpSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Fri Jul 22 12:56:32 CST 2011
     */
    int insertSelective(CpSequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Fri Jul 22 12:56:32 CST 2011
     */
    List<CpSequence> selectByExample(CpSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Fri Jul 22 12:56:32 CST 2011
     */
    int updateByExampleSelective(@Param("record") CpSequence record, @Param("example") CpSequenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CP_SEQUENCE
     *
     * @mbggenerated Fri Jul 22 12:56:32 CST 2011
     */
    int updateByExample(@Param("record") CpSequence record, @Param("example") CpSequenceExample example);
}