package haier.repository.dao;

import haier.repository.model.CrmCustomerBase;
import haier.repository.model.CrmCustomerBaseExample;
import java.util.List;

import haier.view.rms.externalcustomer.LtdratioBean;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface CrmCustomerBaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int countByExample(CrmCustomerBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int deleteByExample(CrmCustomerBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int insert(CrmCustomerBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int insertSelective(CrmCustomerBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    List<CrmCustomerBase> selectByExample(CrmCustomerBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    CrmCustomerBase selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int updateByExampleSelective(@Param("record") CrmCustomerBase record, @Param("example") CrmCustomerBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int updateByExample(@Param("record") CrmCustomerBase record, @Param("example") CrmCustomerBaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int updateByPrimaryKeySelective(CrmCustomerBase record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.CRM_CUSTOMER_BASE
     *
     * @mbggenerated Tue Sep 20 13:45:31 CST 2011
     */
    int updateByPrimaryKey(CrmCustomerBase record);
        @Select(" select distinct aa.actname,aa.deptname from (" +
            " select t.actname,substr(t.actno,12,1) as apcode,m.deptname,sum(t.balamt) balamt,substr(t.txndate,9,2) as days" +
            " from crm_customer_base m join sbs_actbal t on m.custname=t.actname and m.custtype='01' and m.externalflag='1'" +
            " where t.txndate between #{startdate} and #{enddate}" +
            " and t.actname like #{company} and m.deptname like #{dept}" +
            " group by t.actname,substr(t.actno,12,1),t.txndate,m.deptname" +
            " order by t.actname,substr(t.actno,12,1) desc,t.txndate " +
            ") aa order by aa.actname")
    List<LtdratioBean> selectedDistActname(@Param("startdate") String startdate,@Param("enddate") String enddate,
                                           @Param("company") String company,@Param("dept") String dept);
    @Select(" select t.actname,substr(t.actno,12,1) as apcode,m.deptname,sum(t.balamt) balamt,substr(t.txndate,9,2) as days" +
            " from crm_customer_base m join sbs_actbal t on m.custname=t.actname and m.custtype='01' and m.externalflag='1'" +
            " where t.txndate between #{startdate} and #{enddate}" +
            " and t.actname like #{company} and m.deptname like #{dept}" +
            " group by t.actname,substr(t.actno,12,1),t.txndate,m.deptname" +
            " order by t.actname,substr(t.actno,12,1) desc,t.txndate ")
    List<LtdratioBean> selectedLtdratioRecord(@Param("startdate") String startdate,@Param("enddate") String enddate,
                                              @Param("company") String company,@Param("dept") String dept);
}