package haier.repository.dao;

import haier.repository.model.PbcRateDetlverify;
import haier.repository.model.PbcRateDetlverifyExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcRateDetlverifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int countByExample(PbcRateDetlverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int deleteByExample(PbcRateDetlverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int insert(PbcRateDetlverify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int insertSelective(PbcRateDetlverify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    List<PbcRateDetlverify> selectByExample(PbcRateDetlverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    PbcRateDetlverify selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int updateByExampleSelective(@Param("record") PbcRateDetlverify record, @Param("example") PbcRateDetlverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int updateByExample(@Param("record") PbcRateDetlverify record, @Param("example") PbcRateDetlverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int updateByPrimaryKeySelective(PbcRateDetlverify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DETLVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int updateByPrimaryKey(PbcRateDetlverify record);
}