package haier.repository.dao;

import haier.repository.model.PbcRateBalverify;
import haier.repository.model.PbcRateBalverifyExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcRateBalverifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int countByExample(PbcRateBalverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int deleteByExample(PbcRateBalverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int insert(PbcRateBalverify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int insertSelective(PbcRateBalverify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    List<PbcRateBalverify> selectByExample(PbcRateBalverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    PbcRateBalverify selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int updateByExampleSelective(@Param("record") PbcRateBalverify record, @Param("example") PbcRateBalverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int updateByExample(@Param("record") PbcRateBalverify record, @Param("example") PbcRateBalverifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int updateByPrimaryKeySelective(PbcRateBalverify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    int updateByPrimaryKey(PbcRateBalverify record);
}