package haier.repository.dao;

import haier.repository.model.PbcRateDepositbal;
import haier.repository.model.PbcRateDepositbalExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcRateDepositbalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int countByExample(PbcRateDepositbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int deleteByExample(PbcRateDepositbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int insert(PbcRateDepositbal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int insertSelective(PbcRateDepositbal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    List<PbcRateDepositbal> selectByExample(PbcRateDepositbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByExampleSelective(@Param("record") PbcRateDepositbal record, @Param("example") PbcRateDepositbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByExample(@Param("record") PbcRateDepositbal record, @Param("example") PbcRateDepositbalExample example);
}