package haier.repository.dao;

import haier.repository.model.PbcRateLoandetl;
import haier.repository.model.PbcRateLoandetlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcRateLoandetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int countByExample(PbcRateLoandetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int deleteByExample(PbcRateLoandetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int insert(PbcRateLoandetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int insertSelective(PbcRateLoandetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    List<PbcRateLoandetl> selectByExample(PbcRateLoandetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByExampleSelective(@Param("record") PbcRateLoandetl record, @Param("example") PbcRateLoandetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByExample(@Param("record") PbcRateLoandetl record, @Param("example") PbcRateLoandetlExample example);
}