package haier.repository.dao;

import haier.repository.model.PbcRateDepositdetl;
import haier.repository.model.PbcRateDepositdetlExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcRateDepositdetlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int countByExample(PbcRateDepositdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int deleteByExample(PbcRateDepositdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int insert(PbcRateDepositdetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int insertSelective(PbcRateDepositdetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    List<PbcRateDepositdetl> selectByExample(PbcRateDepositdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    PbcRateDepositdetl selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByExampleSelective(@Param("record") PbcRateDepositdetl record, @Param("example") PbcRateDepositdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByExample(@Param("record") PbcRateDepositdetl record, @Param("example") PbcRateDepositdetlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByPrimaryKeySelective(PbcRateDepositdetl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITDETL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByPrimaryKey(PbcRateDepositdetl record);
}