package haier.repository.dao;

import haier.repository.model.PbcRateLoanbal;
import haier.repository.model.PbcRateLoanbalExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface PbcRateLoanbalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int countByExample(PbcRateLoanbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int deleteByExample(PbcRateLoanbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int insert(PbcRateLoanbal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int insertSelective(PbcRateLoanbal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    List<PbcRateLoanbal> selectByExample(PbcRateLoanbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByExampleSelective(@Param("record") PbcRateLoanbal record, @Param("example") PbcRateLoanbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_LOANBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    int updateByExample(@Param("record") PbcRateLoanbal record, @Param("example") PbcRateLoanbalExample example);
}