package haier.repository.dao;

import haier.repository.model.Ptdept;
import haier.repository.model.PtdeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtdeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int countByExample(PtdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int deleteByExample(PtdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int deleteByPrimaryKey(String deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int insert(Ptdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int insertSelective(Ptdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    List<Ptdept> selectByExample(PtdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    Ptdept selectByPrimaryKey(String deptid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int updateByExampleSelective(@Param("record") Ptdept record, @Param("example") PtdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int updateByExample(@Param("record") Ptdept record, @Param("example") PtdeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int updateByPrimaryKeySelective(Ptdept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTDEPT
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int updateByPrimaryKey(Ptdept record);
}