package haier.repository.dao;

import haier.repository.model.Ptmenu;
import haier.repository.model.PtmenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PtmenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int countByExample(PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int deleteByExample(PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int deleteByPrimaryKey(String menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int insert(Ptmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int insertSelective(Ptmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    List<Ptmenu> selectByExample(PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    Ptmenu selectByPrimaryKey(String menuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int updateByExampleSelective(@Param("record") Ptmenu record, @Param("example") PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int updateByExample(@Param("record") Ptmenu record, @Param("example") PtmenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int updateByPrimaryKeySelective(Ptmenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PTMENU
     *
     * @mbggenerated Fri Apr 08 16:05:09 CST 2011
     */
    int updateByPrimaryKey(Ptmenu record);
}