package haier.repository.dao;

import haier.repository.model.S1169Acttype;
import haier.repository.model.S1169ActtypeExample;
import haier.repository.model.S1169ActtypeKey;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface S1169ActtypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int countByExample(S1169ActtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int deleteByExample(S1169ActtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int deleteByPrimaryKey(S1169ActtypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int insert(S1169Acttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int insertSelective(S1169Acttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    List<S1169Acttype> selectByExample(S1169ActtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    S1169Acttype selectByPrimaryKey(S1169ActtypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int updateByExampleSelective(@Param("record") S1169Acttype record, @Param("example") S1169ActtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int updateByExample(@Param("record") S1169Acttype record, @Param("example") S1169ActtypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int updateByPrimaryKeySelective(S1169Acttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    int updateByPrimaryKey(S1169Acttype record);
}