package haier.repository.dao;

import haier.repository.model.SbsActbal;
import haier.repository.model.SbsActbalExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SbsActbalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTBAL
     *
     * @mbggenerated Fri Apr 08 16:08:14 CST 2011
     */
    int countByExample(SbsActbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTBAL
     *
     * @mbggenerated Fri Apr 08 16:08:14 CST 2011
     */
    int deleteByExample(SbsActbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTBAL
     *
     * @mbggenerated Fri Apr 08 16:08:14 CST 2011
     */
    int insert(SbsActbal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTBAL
     *
     * @mbggenerated Fri Apr 08 16:08:14 CST 2011
     */
    int insertSelective(SbsActbal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTBAL
     *
     * @mbggenerated Fri Apr 08 16:08:14 CST 2011
     */
    List<SbsActbal> selectByExample(SbsActbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTBAL
     *
     * @mbggenerated Fri Apr 08 16:08:14 CST 2011
     */
    int updateByExampleSelective(@Param("record") SbsActbal record, @Param("example") SbsActbalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTBAL
     *
     * @mbggenerated Fri Apr 08 16:08:14 CST 2011
     */
    int updateByExample(@Param("record") SbsActbal record, @Param("example") SbsActbalExample example);
}