package haier.repository.dao;

import haier.repository.model.SysLock;
import haier.repository.model.SysLockExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SysLockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Wed Sep 07 10:28:50 CST 2011
     */
    int countByExample(SysLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Wed Sep 07 10:28:50 CST 2011
     */
    int deleteByExample(SysLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Wed Sep 07 10:28:50 CST 2011
     */
    int insert(SysLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Wed Sep 07 10:28:50 CST 2011
     */
    int insertSelective(SysLock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Wed Sep 07 10:28:50 CST 2011
     */
    List<SysLock> selectByExample(SysLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Wed Sep 07 10:28:50 CST 2011
     */
    int updateByExampleSelective(@Param("record") SysLock record, @Param("example") SysLockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_LOCK
     *
     * @mbggenerated Wed Sep 07 10:28:50 CST 2011
     */
    int updateByExample(@Param("record") SysLock record, @Param("example") SysLockExample example);
}