package haier.repository.model;

public class DisActlst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DIS_ACTLST.ACTNAME
     *
     * @mbggenerated Sat Apr 09 20:29:23 CST 2011
     */
    private String actname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DIS_ACTLST.ACTNAME
     *
     * @return the value of DIS_ACTLST.ACTNAME
     *
     * @mbggenerated Sat Apr 09 20:29:23 CST 2011
     */
    public String getActname() {
        return actname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DIS_ACTLST.ACTNAME
     *
     * @param actname the value for DIS_ACTLST.ACTNAME
     *
     * @mbggenerated Sat Apr 09 20:29:23 CST 2011
     */
    public void setActname(String actname) {
        this.actname = actname == null ? null : actname.trim();
    }
}