package haier.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class MtActbalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public MtActbalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBankcdIsNull() {
            addCriterion("BANKCD is null");
            return (Criteria) this;
        }

        public Criteria andBankcdIsNotNull() {
            addCriterion("BANKCD is not null");
            return (Criteria) this;
        }

        public Criteria andBankcdEqualTo(String value) {
            addCriterion("BANKCD =", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdNotEqualTo(String value) {
            addCriterion("BANKCD <>", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdGreaterThan(String value) {
            addCriterion("BANKCD >", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdGreaterThanOrEqualTo(String value) {
            addCriterion("BANKCD >=", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdLessThan(String value) {
            addCriterion("BANKCD <", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdLessThanOrEqualTo(String value) {
            addCriterion("BANKCD <=", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdLike(String value) {
            addCriterion("BANKCD like", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdNotLike(String value) {
            addCriterion("BANKCD not like", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdIn(List<String> values) {
            addCriterion("BANKCD in", values, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdNotIn(List<String> values) {
            addCriterion("BANKCD not in", values, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdBetween(String value1, String value2) {
            addCriterion("BANKCD between", value1, value2, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdNotBetween(String value1, String value2) {
            addCriterion("BANKCD not between", value1, value2, "bankcd");
            return (Criteria) this;
        }

        public Criteria andActnoIsNull() {
            addCriterion("ACTNO is null");
            return (Criteria) this;
        }

        public Criteria andActnoIsNotNull() {
            addCriterion("ACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andActnoEqualTo(String value) {
            addCriterion("ACTNO =", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotEqualTo(String value) {
            addCriterion("ACTNO <>", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoGreaterThan(String value) {
            addCriterion("ACTNO >", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoGreaterThanOrEqualTo(String value) {
            addCriterion("ACTNO >=", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLessThan(String value) {
            addCriterion("ACTNO <", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLessThanOrEqualTo(String value) {
            addCriterion("ACTNO <=", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLike(String value) {
            addCriterion("ACTNO like", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotLike(String value) {
            addCriterion("ACTNO not like", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoIn(List<String> values) {
            addCriterion("ACTNO in", values, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotIn(List<String> values) {
            addCriterion("ACTNO not in", values, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoBetween(String value1, String value2) {
            addCriterion("ACTNO between", value1, value2, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotBetween(String value1, String value2) {
            addCriterion("ACTNO not between", value1, value2, "actno");
            return (Criteria) this;
        }

        public Criteria andBalamtIsNull() {
            addCriterion("BALAMT is null");
            return (Criteria) this;
        }

        public Criteria andBalamtIsNotNull() {
            addCriterion("BALAMT is not null");
            return (Criteria) this;
        }

        public Criteria andBalamtEqualTo(BigDecimal value) {
            addCriterion("BALAMT =", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtNotEqualTo(BigDecimal value) {
            addCriterion("BALAMT <>", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtGreaterThan(BigDecimal value) {
            addCriterion("BALAMT >", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BALAMT >=", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtLessThan(BigDecimal value) {
            addCriterion("BALAMT <", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BALAMT <=", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtIn(List<BigDecimal> values) {
            addCriterion("BALAMT in", values, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtNotIn(List<BigDecimal> values) {
            addCriterion("BALAMT not in", values, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALAMT between", value1, value2, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALAMT not between", value1, value2, "balamt");
            return (Criteria) this;
        }

        public Criteria andExrateIsNull() {
            addCriterion("EXRATE is null");
            return (Criteria) this;
        }

        public Criteria andExrateIsNotNull() {
            addCriterion("EXRATE is not null");
            return (Criteria) this;
        }

        public Criteria andExrateEqualTo(BigDecimal value) {
            addCriterion("EXRATE =", value, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateNotEqualTo(BigDecimal value) {
            addCriterion("EXRATE <>", value, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateGreaterThan(BigDecimal value) {
            addCriterion("EXRATE >", value, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EXRATE >=", value, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateLessThan(BigDecimal value) {
            addCriterion("EXRATE <", value, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EXRATE <=", value, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateIn(List<BigDecimal> values) {
            addCriterion("EXRATE in", values, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateNotIn(List<BigDecimal> values) {
            addCriterion("EXRATE not in", values, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EXRATE between", value1, value2, "exrate");
            return (Criteria) this;
        }

        public Criteria andExrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EXRATE not between", value1, value2, "exrate");
            return (Criteria) this;
        }

        public Criteria andRmbamtIsNull() {
            addCriterion("RMBAMT is null");
            return (Criteria) this;
        }

        public Criteria andRmbamtIsNotNull() {
            addCriterion("RMBAMT is not null");
            return (Criteria) this;
        }

        public Criteria andRmbamtEqualTo(BigDecimal value) {
            addCriterion("RMBAMT =", value, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtNotEqualTo(BigDecimal value) {
            addCriterion("RMBAMT <>", value, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtGreaterThan(BigDecimal value) {
            addCriterion("RMBAMT >", value, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("RMBAMT >=", value, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtLessThan(BigDecimal value) {
            addCriterion("RMBAMT <", value, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("RMBAMT <=", value, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtIn(List<BigDecimal> values) {
            addCriterion("RMBAMT in", values, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtNotIn(List<BigDecimal> values) {
            addCriterion("RMBAMT not in", values, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RMBAMT between", value1, value2, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andRmbamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("RMBAMT not between", value1, value2, "rmbamt");
            return (Criteria) this;
        }

        public Criteria andQrydateIsNull() {
            addCriterion("QRYDATE is null");
            return (Criteria) this;
        }

        public Criteria andQrydateIsNotNull() {
            addCriterion("QRYDATE is not null");
            return (Criteria) this;
        }

        public Criteria andQrydateEqualTo(String value) {
            addCriterion("QRYDATE =", value, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateNotEqualTo(String value) {
            addCriterion("QRYDATE <>", value, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateGreaterThan(String value) {
            addCriterion("QRYDATE >", value, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateGreaterThanOrEqualTo(String value) {
            addCriterion("QRYDATE >=", value, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateLessThan(String value) {
            addCriterion("QRYDATE <", value, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateLessThanOrEqualTo(String value) {
            addCriterion("QRYDATE <=", value, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateLike(String value) {
            addCriterion("QRYDATE like", value, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateNotLike(String value) {
            addCriterion("QRYDATE not like", value, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateIn(List<String> values) {
            addCriterion("QRYDATE in", values, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateNotIn(List<String> values) {
            addCriterion("QRYDATE not in", values, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateBetween(String value1, String value2) {
            addCriterion("QRYDATE between", value1, value2, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrydateNotBetween(String value1, String value2) {
            addCriterion("QRYDATE not between", value1, value2, "qrydate");
            return (Criteria) this;
        }

        public Criteria andQrytimeIsNull() {
            addCriterion("QRYTIME is null");
            return (Criteria) this;
        }

        public Criteria andQrytimeIsNotNull() {
            addCriterion("QRYTIME is not null");
            return (Criteria) this;
        }

        public Criteria andQrytimeEqualTo(String value) {
            addCriterion("QRYTIME =", value, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeNotEqualTo(String value) {
            addCriterion("QRYTIME <>", value, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeGreaterThan(String value) {
            addCriterion("QRYTIME >", value, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeGreaterThanOrEqualTo(String value) {
            addCriterion("QRYTIME >=", value, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeLessThan(String value) {
            addCriterion("QRYTIME <", value, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeLessThanOrEqualTo(String value) {
            addCriterion("QRYTIME <=", value, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeLike(String value) {
            addCriterion("QRYTIME like", value, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeNotLike(String value) {
            addCriterion("QRYTIME not like", value, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeIn(List<String> values) {
            addCriterion("QRYTIME in", values, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeNotIn(List<String> values) {
            addCriterion("QRYTIME not in", values, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeBetween(String value1, String value2) {
            addCriterion("QRYTIME between", value1, value2, "qrytime");
            return (Criteria) this;
        }

        public Criteria andQrytimeNotBetween(String value1, String value2) {
            addCriterion("QRYTIME not between", value1, value2, "qrytime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 22 14:36:14 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table MT_ACTBAL
     *
     * @mbggenerated Wed Jun 22 14:36:14 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}