package haier.repository.model;

import java.math.BigDecimal;

public class PbcRateLoandetl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String reportdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.CUSTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String custtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.ORGANIZATIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String organizationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.INDUSTRYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String industrycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.REGIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String regioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.ECONOMICSECTORCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String economicsectorcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.CORPORATIONSCALECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String corporationscalecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.IOUCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String ioucode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String productstypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.LOANREALINVESTMENTCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String loanrealinvestmentcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.LOANSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String loanstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.LOANENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String loanenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.REALENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String realenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String currencycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.IOUBALAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal ioubalamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String rateflexibletypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal intrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.LOANGUARANTEETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String loanguaranteetypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.LOANSTATUSCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String loanstatuscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.LOANSENDRECVCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String loansendrecvcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_LOANDETL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal usdamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.REPORTDATE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getReportdate() {
        return reportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.REPORTDATE
     *
     * @param reportdate the value for RMS.PBC_RATE_LOANDETL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setReportdate(String reportdate) {
        this.reportdate = reportdate == null ? null : reportdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.BANKCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.BANKCODE
     *
     * @param bankcode the value for RMS.PBC_RATE_LOANDETL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.CUSTTYPE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.CUSTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getCusttype() {
        return custtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.CUSTTYPE
     *
     * @param custtype the value for RMS.PBC_RATE_LOANDETL.CUSTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setCusttype(String custtype) {
        this.custtype = custtype == null ? null : custtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.ORGANIZATIONCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.ORGANIZATIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getOrganizationcode() {
        return organizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.ORGANIZATIONCODE
     *
     * @param organizationcode the value for RMS.PBC_RATE_LOANDETL.ORGANIZATIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setOrganizationcode(String organizationcode) {
        this.organizationcode = organizationcode == null ? null : organizationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.INDUSTRYCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.INDUSTRYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getIndustrycode() {
        return industrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.INDUSTRYCODE
     *
     * @param industrycode the value for RMS.PBC_RATE_LOANDETL.INDUSTRYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setIndustrycode(String industrycode) {
        this.industrycode = industrycode == null ? null : industrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.REGIONCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.REGIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getRegioncode() {
        return regioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.REGIONCODE
     *
     * @param regioncode the value for RMS.PBC_RATE_LOANDETL.REGIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode == null ? null : regioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.ECONOMICSECTORCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.ECONOMICSECTORCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getEconomicsectorcode() {
        return economicsectorcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.ECONOMICSECTORCODE
     *
     * @param economicsectorcode the value for RMS.PBC_RATE_LOANDETL.ECONOMICSECTORCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setEconomicsectorcode(String economicsectorcode) {
        this.economicsectorcode = economicsectorcode == null ? null : economicsectorcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.CORPORATIONSCALECODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.CORPORATIONSCALECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getCorporationscalecode() {
        return corporationscalecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.CORPORATIONSCALECODE
     *
     * @param corporationscalecode the value for RMS.PBC_RATE_LOANDETL.CORPORATIONSCALECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setCorporationscalecode(String corporationscalecode) {
        this.corporationscalecode = corporationscalecode == null ? null : corporationscalecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.IOUCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.IOUCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getIoucode() {
        return ioucode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.IOUCODE
     *
     * @param ioucode the value for RMS.PBC_RATE_LOANDETL.IOUCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setIoucode(String ioucode) {
        this.ioucode = ioucode == null ? null : ioucode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.PRODUCTSTYPECODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getProductstypecode() {
        return productstypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.PRODUCTSTYPECODE
     *
     * @param productstypecode the value for RMS.PBC_RATE_LOANDETL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setProductstypecode(String productstypecode) {
        this.productstypecode = productstypecode == null ? null : productstypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.LOANREALINVESTMENTCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.LOANREALINVESTMENTCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getLoanrealinvestmentcode() {
        return loanrealinvestmentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.LOANREALINVESTMENTCODE
     *
     * @param loanrealinvestmentcode the value for RMS.PBC_RATE_LOANDETL.LOANREALINVESTMENTCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setLoanrealinvestmentcode(String loanrealinvestmentcode) {
        this.loanrealinvestmentcode = loanrealinvestmentcode == null ? null : loanrealinvestmentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.LOANSTARTDATE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.LOANSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getLoanstartdate() {
        return loanstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.LOANSTARTDATE
     *
     * @param loanstartdate the value for RMS.PBC_RATE_LOANDETL.LOANSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setLoanstartdate(String loanstartdate) {
        this.loanstartdate = loanstartdate == null ? null : loanstartdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.LOANENDDATE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.LOANENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getLoanenddate() {
        return loanenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.LOANENDDATE
     *
     * @param loanenddate the value for RMS.PBC_RATE_LOANDETL.LOANENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setLoanenddate(String loanenddate) {
        this.loanenddate = loanenddate == null ? null : loanenddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.REALENDDATE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.REALENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getRealenddate() {
        return realenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.REALENDDATE
     *
     * @param realenddate the value for RMS.PBC_RATE_LOANDETL.REALENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setRealenddate(String realenddate) {
        this.realenddate = realenddate == null ? null : realenddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.CURRENCYCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getCurrencycode() {
        return currencycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.CURRENCYCODE
     *
     * @param currencycode the value for RMS.PBC_RATE_LOANDETL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode == null ? null : currencycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.IOUBALAMT
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.IOUBALAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getIoubalamt() {
        return ioubalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.IOUBALAMT
     *
     * @param ioubalamt the value for RMS.PBC_RATE_LOANDETL.IOUBALAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setIoubalamt(BigDecimal ioubalamt) {
        this.ioubalamt = ioubalamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.RATEFLEXIBLETYPECODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getRateflexibletypecode() {
        return rateflexibletypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.RATEFLEXIBLETYPECODE
     *
     * @param rateflexibletypecode the value for RMS.PBC_RATE_LOANDETL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setRateflexibletypecode(String rateflexibletypecode) {
        this.rateflexibletypecode = rateflexibletypecode == null ? null : rateflexibletypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.INTRATE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getIntrate() {
        return intrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.INTRATE
     *
     * @param intrate the value for RMS.PBC_RATE_LOANDETL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setIntrate(BigDecimal intrate) {
        this.intrate = intrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.LOANGUARANTEETYPECODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.LOANGUARANTEETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getLoanguaranteetypecode() {
        return loanguaranteetypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.LOANGUARANTEETYPECODE
     *
     * @param loanguaranteetypecode the value for RMS.PBC_RATE_LOANDETL.LOANGUARANTEETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setLoanguaranteetypecode(String loanguaranteetypecode) {
        this.loanguaranteetypecode = loanguaranteetypecode == null ? null : loanguaranteetypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.LOANSTATUSCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.LOANSTATUSCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getLoanstatuscode() {
        return loanstatuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.LOANSTATUSCODE
     *
     * @param loanstatuscode the value for RMS.PBC_RATE_LOANDETL.LOANSTATUSCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setLoanstatuscode(String loanstatuscode) {
        this.loanstatuscode = loanstatuscode == null ? null : loanstatuscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.LOANSENDRECVCODE
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.LOANSENDRECVCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getLoansendrecvcode() {
        return loansendrecvcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.LOANSENDRECVCODE
     *
     * @param loansendrecvcode the value for RMS.PBC_RATE_LOANDETL.LOANSENDRECVCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setLoansendrecvcode(String loansendrecvcode) {
        this.loansendrecvcode = loansendrecvcode == null ? null : loansendrecvcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_LOANDETL.USDAMT
     *
     * @return the value of RMS.PBC_RATE_LOANDETL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getUsdamt() {
        return usdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_LOANDETL.USDAMT
     *
     * @param usdamt the value for RMS.PBC_RATE_LOANDETL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setUsdamt(BigDecimal usdamt) {
        this.usdamt = usdamt;
    }
}