package haier.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class PbcRateDepositdetl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.PKID
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.CLIENTNAME
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String clientname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.ORGANIZATIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String organizationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.CERTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String certtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.CERTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String certno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositaccountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositaccounttypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITAGREEMENTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositagreementno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String productstypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String currencycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.AMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal amt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal usdamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String rateflexibletypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal intrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String reportdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.RECVERSION
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private Integer recversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.ARCHIVEFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String archiveflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DELETEDFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String deletedflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DATE_CREATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DATE_UPDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private Date dateUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DATE_DELETE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private Date dateDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITDETL.DATE_ARCHIVE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private Date dateArchive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.PKID
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.PKID
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.PKID
     *
     * @param pkid the value for RMS.PBC_RATE_DEPOSITDETL.PKID
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.BANKCODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.BANKCODE
     *
     * @param bankcode the value for RMS.PBC_RATE_DEPOSITDETL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.CLIENTNAME
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.CLIENTNAME
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getClientname() {
        return clientname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.CLIENTNAME
     *
     * @param clientname the value for RMS.PBC_RATE_DEPOSITDETL.CLIENTNAME
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setClientname(String clientname) {
        this.clientname = clientname == null ? null : clientname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.ORGANIZATIONCODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.ORGANIZATIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getOrganizationcode() {
        return organizationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.ORGANIZATIONCODE
     *
     * @param organizationcode the value for RMS.PBC_RATE_DEPOSITDETL.ORGANIZATIONCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setOrganizationcode(String organizationcode) {
        this.organizationcode = organizationcode == null ? null : organizationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.CERTTYPE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.CERTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getCerttype() {
        return certtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.CERTTYPE
     *
     * @param certtype the value for RMS.PBC_RATE_DEPOSITDETL.CERTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setCerttype(String certtype) {
        this.certtype = certtype == null ? null : certtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.CERTNO
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.CERTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getCertno() {
        return certno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.CERTNO
     *
     * @param certno the value for RMS.PBC_RATE_DEPOSITDETL.CERTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setCertno(String certno) {
        this.certno = certno == null ? null : certno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTNO
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositaccountno() {
        return depositaccountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTNO
     *
     * @param depositaccountno the value for RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositaccountno(String depositaccountno) {
        this.depositaccountno = depositaccountno == null ? null : depositaccountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTTYPECODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositaccounttypecode() {
        return depositaccounttypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTTYPECODE
     *
     * @param depositaccounttypecode the value for RMS.PBC_RATE_DEPOSITDETL.DEPOSITACCOUNTTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositaccounttypecode(String depositaccounttypecode) {
        this.depositaccounttypecode = depositaccounttypecode == null ? null : depositaccounttypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITAGREEMENTNO
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DEPOSITAGREEMENTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositagreementno() {
        return depositagreementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITAGREEMENTNO
     *
     * @param depositagreementno the value for RMS.PBC_RATE_DEPOSITDETL.DEPOSITAGREEMENTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositagreementno(String depositagreementno) {
        this.depositagreementno = depositagreementno == null ? null : depositagreementno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.PRODUCTSTYPECODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getProductstypecode() {
        return productstypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.PRODUCTSTYPECODE
     *
     * @param productstypecode the value for RMS.PBC_RATE_DEPOSITDETL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setProductstypecode(String productstypecode) {
        this.productstypecode = productstypecode == null ? null : productstypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITSTARTDATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DEPOSITSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositstartdate() {
        return depositstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITSTARTDATE
     *
     * @param depositstartdate the value for RMS.PBC_RATE_DEPOSITDETL.DEPOSITSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositstartdate(String depositstartdate) {
        this.depositstartdate = depositstartdate == null ? null : depositstartdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITENDDATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DEPOSITENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositenddate() {
        return depositenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITENDDATE
     *
     * @param depositenddate the value for RMS.PBC_RATE_DEPOSITDETL.DEPOSITENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositenddate(String depositenddate) {
        this.depositenddate = depositenddate == null ? null : depositenddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.CURRENCYCODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getCurrencycode() {
        return currencycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.CURRENCYCODE
     *
     * @param currencycode the value for RMS.PBC_RATE_DEPOSITDETL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode == null ? null : currencycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.AMT
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.AMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.AMT
     *
     * @param amt the value for RMS.PBC_RATE_DEPOSITDETL.AMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.USDAMT
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getUsdamt() {
        return usdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.USDAMT
     *
     * @param usdamt the value for RMS.PBC_RATE_DEPOSITDETL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setUsdamt(BigDecimal usdamt) {
        this.usdamt = usdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.RATEFLEXIBLETYPECODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getRateflexibletypecode() {
        return rateflexibletypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.RATEFLEXIBLETYPECODE
     *
     * @param rateflexibletypecode the value for RMS.PBC_RATE_DEPOSITDETL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setRateflexibletypecode(String rateflexibletypecode) {
        this.rateflexibletypecode = rateflexibletypecode == null ? null : rateflexibletypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.INTRATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getIntrate() {
        return intrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.INTRATE
     *
     * @param intrate the value for RMS.PBC_RATE_DEPOSITDETL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setIntrate(BigDecimal intrate) {
        this.intrate = intrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITFLAG
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DEPOSITFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositflag() {
        return depositflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DEPOSITFLAG
     *
     * @param depositflag the value for RMS.PBC_RATE_DEPOSITDETL.DEPOSITFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositflag(String depositflag) {
        this.depositflag = depositflag == null ? null : depositflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.REPORTDATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getReportdate() {
        return reportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.REPORTDATE
     *
     * @param reportdate the value for RMS.PBC_RATE_DEPOSITDETL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setReportdate(String reportdate) {
        this.reportdate = reportdate == null ? null : reportdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.RECVERSION
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.RECVERSION
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public Integer getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.RECVERSION
     *
     * @param recversion the value for RMS.PBC_RATE_DEPOSITDETL.RECVERSION
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setRecversion(Integer recversion) {
        this.recversion = recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.ARCHIVEFLAG
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.ARCHIVEFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getArchiveflag() {
        return archiveflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.ARCHIVEFLAG
     *
     * @param archiveflag the value for RMS.PBC_RATE_DEPOSITDETL.ARCHIVEFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setArchiveflag(String archiveflag) {
        this.archiveflag = archiveflag == null ? null : archiveflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DELETEDFLAG
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DELETEDFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDeletedflag() {
        return deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DELETEDFLAG
     *
     * @param deletedflag the value for RMS.PBC_RATE_DEPOSITDETL.DELETEDFLAG
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDeletedflag(String deletedflag) {
        this.deletedflag = deletedflag == null ? null : deletedflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DATE_CREATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DATE_CREATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DATE_CREATE
     *
     * @param dateCreate the value for RMS.PBC_RATE_DEPOSITDETL.DATE_CREATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DATE_UPDATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DATE_UPDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public Date getDateUpdate() {
        return dateUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DATE_UPDATE
     *
     * @param dateUpdate the value for RMS.PBC_RATE_DEPOSITDETL.DATE_UPDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDateUpdate(Date dateUpdate) {
        this.dateUpdate = dateUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DATE_DELETE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DATE_DELETE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public Date getDateDelete() {
        return dateDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DATE_DELETE
     *
     * @param dateDelete the value for RMS.PBC_RATE_DEPOSITDETL.DATE_DELETE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDateDelete(Date dateDelete) {
        this.dateDelete = dateDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITDETL.DATE_ARCHIVE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITDETL.DATE_ARCHIVE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public Date getDateArchive() {
        return dateArchive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITDETL.DATE_ARCHIVE
     *
     * @param dateArchive the value for RMS.PBC_RATE_DEPOSITDETL.DATE_ARCHIVE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDateArchive(Date dateArchive) {
        this.dateArchive = dateArchive;
    }
}