package haier.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class PbcRateDepositbalExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public PbcRateDepositbalExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReportdateIsNull() {
            addCriterion("REPORTDATE is null");
            return (Criteria) this;
        }

        public Criteria andReportdateIsNotNull() {
            addCriterion("REPORTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andReportdateEqualTo(String value) {
            addCriterion("REPORTDATE =", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateNotEqualTo(String value) {
            addCriterion("REPORTDATE <>", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateGreaterThan(String value) {
            addCriterion("REPORTDATE >", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateGreaterThanOrEqualTo(String value) {
            addCriterion("REPORTDATE >=", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateLessThan(String value) {
            addCriterion("REPORTDATE <", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateLessThanOrEqualTo(String value) {
            addCriterion("REPORTDATE <=", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateLike(String value) {
            addCriterion("REPORTDATE like", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateNotLike(String value) {
            addCriterion("REPORTDATE not like", value, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateIn(List<String> values) {
            addCriterion("REPORTDATE in", values, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateNotIn(List<String> values) {
            addCriterion("REPORTDATE not in", values, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateBetween(String value1, String value2) {
            addCriterion("REPORTDATE between", value1, value2, "reportdate");
            return (Criteria) this;
        }

        public Criteria andReportdateNotBetween(String value1, String value2) {
            addCriterion("REPORTDATE not between", value1, value2, "reportdate");
            return (Criteria) this;
        }

        public Criteria andBankcodeIsNull() {
            addCriterion("BANKCODE is null");
            return (Criteria) this;
        }

        public Criteria andBankcodeIsNotNull() {
            addCriterion("BANKCODE is not null");
            return (Criteria) this;
        }

        public Criteria andBankcodeEqualTo(String value) {
            addCriterion("BANKCODE =", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotEqualTo(String value) {
            addCriterion("BANKCODE <>", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeGreaterThan(String value) {
            addCriterion("BANKCODE >", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeGreaterThanOrEqualTo(String value) {
            addCriterion("BANKCODE >=", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLessThan(String value) {
            addCriterion("BANKCODE <", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLessThanOrEqualTo(String value) {
            addCriterion("BANKCODE <=", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeLike(String value) {
            addCriterion("BANKCODE like", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotLike(String value) {
            addCriterion("BANKCODE not like", value, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeIn(List<String> values) {
            addCriterion("BANKCODE in", values, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotIn(List<String> values) {
            addCriterion("BANKCODE not in", values, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeBetween(String value1, String value2) {
            addCriterion("BANKCODE between", value1, value2, "bankcode");
            return (Criteria) this;
        }

        public Criteria andBankcodeNotBetween(String value1, String value2) {
            addCriterion("BANKCODE not between", value1, value2, "bankcode");
            return (Criteria) this;
        }

        public Criteria andCusttypeIsNull() {
            addCriterion("CUSTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andCusttypeIsNotNull() {
            addCriterion("CUSTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andCusttypeEqualTo(String value) {
            addCriterion("CUSTTYPE =", value, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeNotEqualTo(String value) {
            addCriterion("CUSTTYPE <>", value, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeGreaterThan(String value) {
            addCriterion("CUSTTYPE >", value, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeGreaterThanOrEqualTo(String value) {
            addCriterion("CUSTTYPE >=", value, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeLessThan(String value) {
            addCriterion("CUSTTYPE <", value, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeLessThanOrEqualTo(String value) {
            addCriterion("CUSTTYPE <=", value, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeLike(String value) {
            addCriterion("CUSTTYPE like", value, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeNotLike(String value) {
            addCriterion("CUSTTYPE not like", value, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeIn(List<String> values) {
            addCriterion("CUSTTYPE in", values, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeNotIn(List<String> values) {
            addCriterion("CUSTTYPE not in", values, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeBetween(String value1, String value2) {
            addCriterion("CUSTTYPE between", value1, value2, "custtype");
            return (Criteria) this;
        }

        public Criteria andCusttypeNotBetween(String value1, String value2) {
            addCriterion("CUSTTYPE not between", value1, value2, "custtype");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoIsNull() {
            addCriterion("DEPOSITACCOUNTNO is null");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoIsNotNull() {
            addCriterion("DEPOSITACCOUNTNO is not null");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoEqualTo(String value) {
            addCriterion("DEPOSITACCOUNTNO =", value, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoNotEqualTo(String value) {
            addCriterion("DEPOSITACCOUNTNO <>", value, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoGreaterThan(String value) {
            addCriterion("DEPOSITACCOUNTNO >", value, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoGreaterThanOrEqualTo(String value) {
            addCriterion("DEPOSITACCOUNTNO >=", value, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoLessThan(String value) {
            addCriterion("DEPOSITACCOUNTNO <", value, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoLessThanOrEqualTo(String value) {
            addCriterion("DEPOSITACCOUNTNO <=", value, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoLike(String value) {
            addCriterion("DEPOSITACCOUNTNO like", value, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoNotLike(String value) {
            addCriterion("DEPOSITACCOUNTNO not like", value, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoIn(List<String> values) {
            addCriterion("DEPOSITACCOUNTNO in", values, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoNotIn(List<String> values) {
            addCriterion("DEPOSITACCOUNTNO not in", values, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoBetween(String value1, String value2) {
            addCriterion("DEPOSITACCOUNTNO between", value1, value2, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositaccountnoNotBetween(String value1, String value2) {
            addCriterion("DEPOSITACCOUNTNO not between", value1, value2, "depositaccountno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoIsNull() {
            addCriterion("DEPOSITAGREEMENTNO is null");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoIsNotNull() {
            addCriterion("DEPOSITAGREEMENTNO is not null");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoEqualTo(String value) {
            addCriterion("DEPOSITAGREEMENTNO =", value, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoNotEqualTo(String value) {
            addCriterion("DEPOSITAGREEMENTNO <>", value, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoGreaterThan(String value) {
            addCriterion("DEPOSITAGREEMENTNO >", value, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoGreaterThanOrEqualTo(String value) {
            addCriterion("DEPOSITAGREEMENTNO >=", value, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoLessThan(String value) {
            addCriterion("DEPOSITAGREEMENTNO <", value, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoLessThanOrEqualTo(String value) {
            addCriterion("DEPOSITAGREEMENTNO <=", value, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoLike(String value) {
            addCriterion("DEPOSITAGREEMENTNO like", value, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoNotLike(String value) {
            addCriterion("DEPOSITAGREEMENTNO not like", value, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoIn(List<String> values) {
            addCriterion("DEPOSITAGREEMENTNO in", values, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoNotIn(List<String> values) {
            addCriterion("DEPOSITAGREEMENTNO not in", values, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoBetween(String value1, String value2) {
            addCriterion("DEPOSITAGREEMENTNO between", value1, value2, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andDepositagreementnoNotBetween(String value1, String value2) {
            addCriterion("DEPOSITAGREEMENTNO not between", value1, value2, "depositagreementno");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeIsNull() {
            addCriterion("PRODUCTSTYPECODE is null");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeIsNotNull() {
            addCriterion("PRODUCTSTYPECODE is not null");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeEqualTo(String value) {
            addCriterion("PRODUCTSTYPECODE =", value, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeNotEqualTo(String value) {
            addCriterion("PRODUCTSTYPECODE <>", value, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeGreaterThan(String value) {
            addCriterion("PRODUCTSTYPECODE >", value, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCTSTYPECODE >=", value, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeLessThan(String value) {
            addCriterion("PRODUCTSTYPECODE <", value, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeLessThanOrEqualTo(String value) {
            addCriterion("PRODUCTSTYPECODE <=", value, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeLike(String value) {
            addCriterion("PRODUCTSTYPECODE like", value, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeNotLike(String value) {
            addCriterion("PRODUCTSTYPECODE not like", value, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeIn(List<String> values) {
            addCriterion("PRODUCTSTYPECODE in", values, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeNotIn(List<String> values) {
            addCriterion("PRODUCTSTYPECODE not in", values, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeBetween(String value1, String value2) {
            addCriterion("PRODUCTSTYPECODE between", value1, value2, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andProductstypecodeNotBetween(String value1, String value2) {
            addCriterion("PRODUCTSTYPECODE not between", value1, value2, "productstypecode");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateIsNull() {
            addCriterion("DEPOSITSTARTDATE is null");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateIsNotNull() {
            addCriterion("DEPOSITSTARTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateEqualTo(String value) {
            addCriterion("DEPOSITSTARTDATE =", value, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateNotEqualTo(String value) {
            addCriterion("DEPOSITSTARTDATE <>", value, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateGreaterThan(String value) {
            addCriterion("DEPOSITSTARTDATE >", value, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateGreaterThanOrEqualTo(String value) {
            addCriterion("DEPOSITSTARTDATE >=", value, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateLessThan(String value) {
            addCriterion("DEPOSITSTARTDATE <", value, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateLessThanOrEqualTo(String value) {
            addCriterion("DEPOSITSTARTDATE <=", value, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateLike(String value) {
            addCriterion("DEPOSITSTARTDATE like", value, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateNotLike(String value) {
            addCriterion("DEPOSITSTARTDATE not like", value, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateIn(List<String> values) {
            addCriterion("DEPOSITSTARTDATE in", values, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateNotIn(List<String> values) {
            addCriterion("DEPOSITSTARTDATE not in", values, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateBetween(String value1, String value2) {
            addCriterion("DEPOSITSTARTDATE between", value1, value2, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositstartdateNotBetween(String value1, String value2) {
            addCriterion("DEPOSITSTARTDATE not between", value1, value2, "depositstartdate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateIsNull() {
            addCriterion("DEPOSITENDDATE is null");
            return (Criteria) this;
        }

        public Criteria andDepositenddateIsNotNull() {
            addCriterion("DEPOSITENDDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDepositenddateEqualTo(String value) {
            addCriterion("DEPOSITENDDATE =", value, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateNotEqualTo(String value) {
            addCriterion("DEPOSITENDDATE <>", value, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateGreaterThan(String value) {
            addCriterion("DEPOSITENDDATE >", value, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateGreaterThanOrEqualTo(String value) {
            addCriterion("DEPOSITENDDATE >=", value, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateLessThan(String value) {
            addCriterion("DEPOSITENDDATE <", value, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateLessThanOrEqualTo(String value) {
            addCriterion("DEPOSITENDDATE <=", value, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateLike(String value) {
            addCriterion("DEPOSITENDDATE like", value, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateNotLike(String value) {
            addCriterion("DEPOSITENDDATE not like", value, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateIn(List<String> values) {
            addCriterion("DEPOSITENDDATE in", values, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateNotIn(List<String> values) {
            addCriterion("DEPOSITENDDATE not in", values, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateBetween(String value1, String value2) {
            addCriterion("DEPOSITENDDATE between", value1, value2, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andDepositenddateNotBetween(String value1, String value2) {
            addCriterion("DEPOSITENDDATE not between", value1, value2, "depositenddate");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeIsNull() {
            addCriterion("CURRENCYCODE is null");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeIsNotNull() {
            addCriterion("CURRENCYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeEqualTo(String value) {
            addCriterion("CURRENCYCODE =", value, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeNotEqualTo(String value) {
            addCriterion("CURRENCYCODE <>", value, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeGreaterThan(String value) {
            addCriterion("CURRENCYCODE >", value, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENCYCODE >=", value, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeLessThan(String value) {
            addCriterion("CURRENCYCODE <", value, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeLessThanOrEqualTo(String value) {
            addCriterion("CURRENCYCODE <=", value, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeLike(String value) {
            addCriterion("CURRENCYCODE like", value, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeNotLike(String value) {
            addCriterion("CURRENCYCODE not like", value, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeIn(List<String> values) {
            addCriterion("CURRENCYCODE in", values, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeNotIn(List<String> values) {
            addCriterion("CURRENCYCODE not in", values, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeBetween(String value1, String value2) {
            addCriterion("CURRENCYCODE between", value1, value2, "currencycode");
            return (Criteria) this;
        }

        public Criteria andCurrencycodeNotBetween(String value1, String value2) {
            addCriterion("CURRENCYCODE not between", value1, value2, "currencycode");
            return (Criteria) this;
        }

        public Criteria andBalamtIsNull() {
            addCriterion("BALAMT is null");
            return (Criteria) this;
        }

        public Criteria andBalamtIsNotNull() {
            addCriterion("BALAMT is not null");
            return (Criteria) this;
        }

        public Criteria andBalamtEqualTo(BigDecimal value) {
            addCriterion("BALAMT =", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtNotEqualTo(BigDecimal value) {
            addCriterion("BALAMT <>", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtGreaterThan(BigDecimal value) {
            addCriterion("BALAMT >", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("BALAMT >=", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtLessThan(BigDecimal value) {
            addCriterion("BALAMT <", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("BALAMT <=", value, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtIn(List<BigDecimal> values) {
            addCriterion("BALAMT in", values, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtNotIn(List<BigDecimal> values) {
            addCriterion("BALAMT not in", values, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALAMT between", value1, value2, "balamt");
            return (Criteria) this;
        }

        public Criteria andBalamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("BALAMT not between", value1, value2, "balamt");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeIsNull() {
            addCriterion("RATEFLEXIBLETYPECODE is null");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeIsNotNull() {
            addCriterion("RATEFLEXIBLETYPECODE is not null");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeEqualTo(String value) {
            addCriterion("RATEFLEXIBLETYPECODE =", value, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeNotEqualTo(String value) {
            addCriterion("RATEFLEXIBLETYPECODE <>", value, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeGreaterThan(String value) {
            addCriterion("RATEFLEXIBLETYPECODE >", value, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeGreaterThanOrEqualTo(String value) {
            addCriterion("RATEFLEXIBLETYPECODE >=", value, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeLessThan(String value) {
            addCriterion("RATEFLEXIBLETYPECODE <", value, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeLessThanOrEqualTo(String value) {
            addCriterion("RATEFLEXIBLETYPECODE <=", value, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeLike(String value) {
            addCriterion("RATEFLEXIBLETYPECODE like", value, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeNotLike(String value) {
            addCriterion("RATEFLEXIBLETYPECODE not like", value, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeIn(List<String> values) {
            addCriterion("RATEFLEXIBLETYPECODE in", values, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeNotIn(List<String> values) {
            addCriterion("RATEFLEXIBLETYPECODE not in", values, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeBetween(String value1, String value2) {
            addCriterion("RATEFLEXIBLETYPECODE between", value1, value2, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andRateflexibletypecodeNotBetween(String value1, String value2) {
            addCriterion("RATEFLEXIBLETYPECODE not between", value1, value2, "rateflexibletypecode");
            return (Criteria) this;
        }

        public Criteria andIntrateIsNull() {
            addCriterion("INTRATE is null");
            return (Criteria) this;
        }

        public Criteria andIntrateIsNotNull() {
            addCriterion("INTRATE is not null");
            return (Criteria) this;
        }

        public Criteria andIntrateEqualTo(BigDecimal value) {
            addCriterion("INTRATE =", value, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateNotEqualTo(BigDecimal value) {
            addCriterion("INTRATE <>", value, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateGreaterThan(BigDecimal value) {
            addCriterion("INTRATE >", value, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("INTRATE >=", value, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateLessThan(BigDecimal value) {
            addCriterion("INTRATE <", value, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("INTRATE <=", value, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateIn(List<BigDecimal> values) {
            addCriterion("INTRATE in", values, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateNotIn(List<BigDecimal> values) {
            addCriterion("INTRATE not in", values, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTRATE between", value1, value2, "intrate");
            return (Criteria) this;
        }

        public Criteria andIntrateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("INTRATE not between", value1, value2, "intrate");
            return (Criteria) this;
        }

        public Criteria andUsdamtIsNull() {
            addCriterion("USDAMT is null");
            return (Criteria) this;
        }

        public Criteria andUsdamtIsNotNull() {
            addCriterion("USDAMT is not null");
            return (Criteria) this;
        }

        public Criteria andUsdamtEqualTo(BigDecimal value) {
            addCriterion("USDAMT =", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtNotEqualTo(BigDecimal value) {
            addCriterion("USDAMT <>", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtGreaterThan(BigDecimal value) {
            addCriterion("USDAMT >", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USDAMT >=", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtLessThan(BigDecimal value) {
            addCriterion("USDAMT <", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USDAMT <=", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtIn(List<BigDecimal> values) {
            addCriterion("USDAMT in", values, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtNotIn(List<BigDecimal> values) {
            addCriterion("USDAMT not in", values, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USDAMT between", value1, value2, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USDAMT not between", value1, value2, "usdamt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 18 12:06:34 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.PBC_RATE_DEPOSITBAL
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}