package haier.repository.model;

import java.math.BigDecimal;
import java.util.Date;

public class PbcRateDetlverify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.PKID
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private String pkid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.RPTTYPE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private String rpttype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.ITEMCODE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private String itemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.ITEMNAME
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private String itemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.LMBALCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private BigDecimal lmbalcnyamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.LMBALUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private BigDecimal lmbalusdamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.VERIFYCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private BigDecimal verifycnyamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.VERIFYUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private BigDecimal verifyusdamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.CMBALCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private BigDecimal cmbalcnyamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.CMBALUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private BigDecimal cmbalusdamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.CMDETLCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private BigDecimal cmdetlcnyamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.CMDETLUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private BigDecimal cmdetlusdamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.RPTDATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private String rptdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.RECVERSION
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private Integer recversion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.ARCHIVEFLAG
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private String archiveflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.DELETEDFLAG
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private String deletedflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.DATE_CREATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.DATE_UPDATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private Date dateUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.DATE_DELETE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private Date dateDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DETLVERIFY.DATE_ARCHIVE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    private Date dateArchive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.PKID
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.PKID
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public String getPkid() {
        return pkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.PKID
     *
     * @param pkid the value for RMS.PBC_RATE_DETLVERIFY.PKID
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setPkid(String pkid) {
        this.pkid = pkid == null ? null : pkid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.RPTTYPE
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.RPTTYPE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public String getRpttype() {
        return rpttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.RPTTYPE
     *
     * @param rpttype the value for RMS.PBC_RATE_DETLVERIFY.RPTTYPE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setRpttype(String rpttype) {
        this.rpttype = rpttype == null ? null : rpttype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.ITEMCODE
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.ITEMCODE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public String getItemcode() {
        return itemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.ITEMCODE
     *
     * @param itemcode the value for RMS.PBC_RATE_DETLVERIFY.ITEMCODE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setItemcode(String itemcode) {
        this.itemcode = itemcode == null ? null : itemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.ITEMNAME
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.ITEMNAME
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.ITEMNAME
     *
     * @param itemname the value for RMS.PBC_RATE_DETLVERIFY.ITEMNAME
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.LMBALCNYAMT
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.LMBALCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public BigDecimal getLmbalcnyamt() {
        return lmbalcnyamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.LMBALCNYAMT
     *
     * @param lmbalcnyamt the value for RMS.PBC_RATE_DETLVERIFY.LMBALCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setLmbalcnyamt(BigDecimal lmbalcnyamt) {
        this.lmbalcnyamt = lmbalcnyamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.LMBALUSDAMT
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.LMBALUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public BigDecimal getLmbalusdamt() {
        return lmbalusdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.LMBALUSDAMT
     *
     * @param lmbalusdamt the value for RMS.PBC_RATE_DETLVERIFY.LMBALUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setLmbalusdamt(BigDecimal lmbalusdamt) {
        this.lmbalusdamt = lmbalusdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.VERIFYCNYAMT
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.VERIFYCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public BigDecimal getVerifycnyamt() {
        return verifycnyamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.VERIFYCNYAMT
     *
     * @param verifycnyamt the value for RMS.PBC_RATE_DETLVERIFY.VERIFYCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setVerifycnyamt(BigDecimal verifycnyamt) {
        this.verifycnyamt = verifycnyamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.VERIFYUSDAMT
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.VERIFYUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public BigDecimal getVerifyusdamt() {
        return verifyusdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.VERIFYUSDAMT
     *
     * @param verifyusdamt the value for RMS.PBC_RATE_DETLVERIFY.VERIFYUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setVerifyusdamt(BigDecimal verifyusdamt) {
        this.verifyusdamt = verifyusdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.CMBALCNYAMT
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.CMBALCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public BigDecimal getCmbalcnyamt() {
        return cmbalcnyamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.CMBALCNYAMT
     *
     * @param cmbalcnyamt the value for RMS.PBC_RATE_DETLVERIFY.CMBALCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setCmbalcnyamt(BigDecimal cmbalcnyamt) {
        this.cmbalcnyamt = cmbalcnyamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.CMBALUSDAMT
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.CMBALUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public BigDecimal getCmbalusdamt() {
        return cmbalusdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.CMBALUSDAMT
     *
     * @param cmbalusdamt the value for RMS.PBC_RATE_DETLVERIFY.CMBALUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setCmbalusdamt(BigDecimal cmbalusdamt) {
        this.cmbalusdamt = cmbalusdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.CMDETLCNYAMT
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.CMDETLCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public BigDecimal getCmdetlcnyamt() {
        return cmdetlcnyamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.CMDETLCNYAMT
     *
     * @param cmdetlcnyamt the value for RMS.PBC_RATE_DETLVERIFY.CMDETLCNYAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setCmdetlcnyamt(BigDecimal cmdetlcnyamt) {
        this.cmdetlcnyamt = cmdetlcnyamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.CMDETLUSDAMT
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.CMDETLUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public BigDecimal getCmdetlusdamt() {
        return cmdetlusdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.CMDETLUSDAMT
     *
     * @param cmdetlusdamt the value for RMS.PBC_RATE_DETLVERIFY.CMDETLUSDAMT
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setCmdetlusdamt(BigDecimal cmdetlusdamt) {
        this.cmdetlusdamt = cmdetlusdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.RPTDATE
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.RPTDATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public String getRptdate() {
        return rptdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.RPTDATE
     *
     * @param rptdate the value for RMS.PBC_RATE_DETLVERIFY.RPTDATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setRptdate(String rptdate) {
        this.rptdate = rptdate == null ? null : rptdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.RECVERSION
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.RECVERSION
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public Integer getRecversion() {
        return recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.RECVERSION
     *
     * @param recversion the value for RMS.PBC_RATE_DETLVERIFY.RECVERSION
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setRecversion(Integer recversion) {
        this.recversion = recversion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.ARCHIVEFLAG
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.ARCHIVEFLAG
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public String getArchiveflag() {
        return archiveflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.ARCHIVEFLAG
     *
     * @param archiveflag the value for RMS.PBC_RATE_DETLVERIFY.ARCHIVEFLAG
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setArchiveflag(String archiveflag) {
        this.archiveflag = archiveflag == null ? null : archiveflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.DELETEDFLAG
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.DELETEDFLAG
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public String getDeletedflag() {
        return deletedflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.DELETEDFLAG
     *
     * @param deletedflag the value for RMS.PBC_RATE_DETLVERIFY.DELETEDFLAG
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setDeletedflag(String deletedflag) {
        this.deletedflag = deletedflag == null ? null : deletedflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.DATE_CREATE
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.DATE_CREATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.DATE_CREATE
     *
     * @param dateCreate the value for RMS.PBC_RATE_DETLVERIFY.DATE_CREATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.DATE_UPDATE
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.DATE_UPDATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public Date getDateUpdate() {
        return dateUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.DATE_UPDATE
     *
     * @param dateUpdate the value for RMS.PBC_RATE_DETLVERIFY.DATE_UPDATE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setDateUpdate(Date dateUpdate) {
        this.dateUpdate = dateUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.DATE_DELETE
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.DATE_DELETE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public Date getDateDelete() {
        return dateDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.DATE_DELETE
     *
     * @param dateDelete the value for RMS.PBC_RATE_DETLVERIFY.DATE_DELETE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setDateDelete(Date dateDelete) {
        this.dateDelete = dateDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DETLVERIFY.DATE_ARCHIVE
     *
     * @return the value of RMS.PBC_RATE_DETLVERIFY.DATE_ARCHIVE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public Date getDateArchive() {
        return dateArchive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DETLVERIFY.DATE_ARCHIVE
     *
     * @param dateArchive the value for RMS.PBC_RATE_DETLVERIFY.DATE_ARCHIVE
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setDateArchive(Date dateArchive) {
        this.dateArchive = dateArchive;
    }
}