package haier.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PbcRateBalverifyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public PbcRateBalverifyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andRpttypeIsNull() {
            addCriterion("RPTTYPE is null");
            return (Criteria) this;
        }

        public Criteria andRpttypeIsNotNull() {
            addCriterion("RPTTYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRpttypeEqualTo(String value) {
            addCriterion("RPTTYPE =", value, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeNotEqualTo(String value) {
            addCriterion("RPTTYPE <>", value, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeGreaterThan(String value) {
            addCriterion("RPTTYPE >", value, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeGreaterThanOrEqualTo(String value) {
            addCriterion("RPTTYPE >=", value, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeLessThan(String value) {
            addCriterion("RPTTYPE <", value, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeLessThanOrEqualTo(String value) {
            addCriterion("RPTTYPE <=", value, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeLike(String value) {
            addCriterion("RPTTYPE like", value, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeNotLike(String value) {
            addCriterion("RPTTYPE not like", value, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeIn(List<String> values) {
            addCriterion("RPTTYPE in", values, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeNotIn(List<String> values) {
            addCriterion("RPTTYPE not in", values, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeBetween(String value1, String value2) {
            addCriterion("RPTTYPE between", value1, value2, "rpttype");
            return (Criteria) this;
        }

        public Criteria andRpttypeNotBetween(String value1, String value2) {
            addCriterion("RPTTYPE not between", value1, value2, "rpttype");
            return (Criteria) this;
        }

        public Criteria andItemcodeIsNull() {
            addCriterion("ITEMCODE is null");
            return (Criteria) this;
        }

        public Criteria andItemcodeIsNotNull() {
            addCriterion("ITEMCODE is not null");
            return (Criteria) this;
        }

        public Criteria andItemcodeEqualTo(String value) {
            addCriterion("ITEMCODE =", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotEqualTo(String value) {
            addCriterion("ITEMCODE <>", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeGreaterThan(String value) {
            addCriterion("ITEMCODE >", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeGreaterThanOrEqualTo(String value) {
            addCriterion("ITEMCODE >=", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLessThan(String value) {
            addCriterion("ITEMCODE <", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLessThanOrEqualTo(String value) {
            addCriterion("ITEMCODE <=", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeLike(String value) {
            addCriterion("ITEMCODE like", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotLike(String value) {
            addCriterion("ITEMCODE not like", value, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeIn(List<String> values) {
            addCriterion("ITEMCODE in", values, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotIn(List<String> values) {
            addCriterion("ITEMCODE not in", values, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeBetween(String value1, String value2) {
            addCriterion("ITEMCODE between", value1, value2, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemcodeNotBetween(String value1, String value2) {
            addCriterion("ITEMCODE not between", value1, value2, "itemcode");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNull() {
            addCriterion("ITEMNAME is null");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNotNull() {
            addCriterion("ITEMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andItemnameEqualTo(String value) {
            addCriterion("ITEMNAME =", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotEqualTo(String value) {
            addCriterion("ITEMNAME <>", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThan(String value) {
            addCriterion("ITEMNAME >", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThanOrEqualTo(String value) {
            addCriterion("ITEMNAME >=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThan(String value) {
            addCriterion("ITEMNAME <", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThanOrEqualTo(String value) {
            addCriterion("ITEMNAME <=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLike(String value) {
            addCriterion("ITEMNAME like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotLike(String value) {
            addCriterion("ITEMNAME not like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameIn(List<String> values) {
            addCriterion("ITEMNAME in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotIn(List<String> values) {
            addCriterion("ITEMNAME not in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameBetween(String value1, String value2) {
            addCriterion("ITEMNAME between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotBetween(String value1, String value2) {
            addCriterion("ITEMNAME not between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andCnyamtIsNull() {
            addCriterion("CNYAMT is null");
            return (Criteria) this;
        }

        public Criteria andCnyamtIsNotNull() {
            addCriterion("CNYAMT is not null");
            return (Criteria) this;
        }

        public Criteria andCnyamtEqualTo(BigDecimal value) {
            addCriterion("CNYAMT =", value, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtNotEqualTo(BigDecimal value) {
            addCriterion("CNYAMT <>", value, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtGreaterThan(BigDecimal value) {
            addCriterion("CNYAMT >", value, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CNYAMT >=", value, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtLessThan(BigDecimal value) {
            addCriterion("CNYAMT <", value, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CNYAMT <=", value, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtIn(List<BigDecimal> values) {
            addCriterion("CNYAMT in", values, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtNotIn(List<BigDecimal> values) {
            addCriterion("CNYAMT not in", values, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CNYAMT between", value1, value2, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andCnyamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CNYAMT not between", value1, value2, "cnyamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtIsNull() {
            addCriterion("USDAMT is null");
            return (Criteria) this;
        }

        public Criteria andUsdamtIsNotNull() {
            addCriterion("USDAMT is not null");
            return (Criteria) this;
        }

        public Criteria andUsdamtEqualTo(BigDecimal value) {
            addCriterion("USDAMT =", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtNotEqualTo(BigDecimal value) {
            addCriterion("USDAMT <>", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtGreaterThan(BigDecimal value) {
            addCriterion("USDAMT >", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USDAMT >=", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtLessThan(BigDecimal value) {
            addCriterion("USDAMT <", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USDAMT <=", value, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtIn(List<BigDecimal> values) {
            addCriterion("USDAMT in", values, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtNotIn(List<BigDecimal> values) {
            addCriterion("USDAMT not in", values, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USDAMT between", value1, value2, "usdamt");
            return (Criteria) this;
        }

        public Criteria andUsdamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USDAMT not between", value1, value2, "usdamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtIsNull() {
            addCriterion("VERIFYCNYAMT is null");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtIsNotNull() {
            addCriterion("VERIFYCNYAMT is not null");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtEqualTo(BigDecimal value) {
            addCriterion("VERIFYCNYAMT =", value, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtNotEqualTo(BigDecimal value) {
            addCriterion("VERIFYCNYAMT <>", value, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtGreaterThan(BigDecimal value) {
            addCriterion("VERIFYCNYAMT >", value, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERIFYCNYAMT >=", value, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtLessThan(BigDecimal value) {
            addCriterion("VERIFYCNYAMT <", value, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERIFYCNYAMT <=", value, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtIn(List<BigDecimal> values) {
            addCriterion("VERIFYCNYAMT in", values, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtNotIn(List<BigDecimal> values) {
            addCriterion("VERIFYCNYAMT not in", values, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERIFYCNYAMT between", value1, value2, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifycnyamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERIFYCNYAMT not between", value1, value2, "verifycnyamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtIsNull() {
            addCriterion("VERIFYUSDAMT is null");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtIsNotNull() {
            addCriterion("VERIFYUSDAMT is not null");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtEqualTo(BigDecimal value) {
            addCriterion("VERIFYUSDAMT =", value, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtNotEqualTo(BigDecimal value) {
            addCriterion("VERIFYUSDAMT <>", value, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtGreaterThan(BigDecimal value) {
            addCriterion("VERIFYUSDAMT >", value, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("VERIFYUSDAMT >=", value, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtLessThan(BigDecimal value) {
            addCriterion("VERIFYUSDAMT <", value, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("VERIFYUSDAMT <=", value, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtIn(List<BigDecimal> values) {
            addCriterion("VERIFYUSDAMT in", values, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtNotIn(List<BigDecimal> values) {
            addCriterion("VERIFYUSDAMT not in", values, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERIFYUSDAMT between", value1, value2, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andVerifyusdamtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("VERIFYUSDAMT not between", value1, value2, "verifyusdamt");
            return (Criteria) this;
        }

        public Criteria andA1411amtIsNull() {
            addCriterion("A1411AMT is null");
            return (Criteria) this;
        }

        public Criteria andA1411amtIsNotNull() {
            addCriterion("A1411AMT is not null");
            return (Criteria) this;
        }

        public Criteria andA1411amtEqualTo(BigDecimal value) {
            addCriterion("A1411AMT =", value, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtNotEqualTo(BigDecimal value) {
            addCriterion("A1411AMT <>", value, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtGreaterThan(BigDecimal value) {
            addCriterion("A1411AMT >", value, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("A1411AMT >=", value, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtLessThan(BigDecimal value) {
            addCriterion("A1411AMT <", value, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("A1411AMT <=", value, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtIn(List<BigDecimal> values) {
            addCriterion("A1411AMT in", values, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtNotIn(List<BigDecimal> values) {
            addCriterion("A1411AMT not in", values, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("A1411AMT between", value1, value2, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA1411amtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("A1411AMT not between", value1, value2, "a1411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtIsNull() {
            addCriterion("A2411AMT is null");
            return (Criteria) this;
        }

        public Criteria andA2411amtIsNotNull() {
            addCriterion("A2411AMT is not null");
            return (Criteria) this;
        }

        public Criteria andA2411amtEqualTo(BigDecimal value) {
            addCriterion("A2411AMT =", value, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtNotEqualTo(BigDecimal value) {
            addCriterion("A2411AMT <>", value, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtGreaterThan(BigDecimal value) {
            addCriterion("A2411AMT >", value, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("A2411AMT >=", value, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtLessThan(BigDecimal value) {
            addCriterion("A2411AMT <", value, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("A2411AMT <=", value, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtIn(List<BigDecimal> values) {
            addCriterion("A2411AMT in", values, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtNotIn(List<BigDecimal> values) {
            addCriterion("A2411AMT not in", values, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("A2411AMT between", value1, value2, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andA2411amtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("A2411AMT not between", value1, value2, "a2411amt");
            return (Criteria) this;
        }

        public Criteria andRptdateIsNull() {
            addCriterion("RPTDATE is null");
            return (Criteria) this;
        }

        public Criteria andRptdateIsNotNull() {
            addCriterion("RPTDATE is not null");
            return (Criteria) this;
        }

        public Criteria andRptdateEqualTo(String value) {
            addCriterion("RPTDATE =", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateNotEqualTo(String value) {
            addCriterion("RPTDATE <>", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateGreaterThan(String value) {
            addCriterion("RPTDATE >", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateGreaterThanOrEqualTo(String value) {
            addCriterion("RPTDATE >=", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateLessThan(String value) {
            addCriterion("RPTDATE <", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateLessThanOrEqualTo(String value) {
            addCriterion("RPTDATE <=", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateLike(String value) {
            addCriterion("RPTDATE like", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateNotLike(String value) {
            addCriterion("RPTDATE not like", value, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateIn(List<String> values) {
            addCriterion("RPTDATE in", values, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateNotIn(List<String> values) {
            addCriterion("RPTDATE not in", values, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateBetween(String value1, String value2) {
            addCriterion("RPTDATE between", value1, value2, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRptdateNotBetween(String value1, String value2) {
            addCriterion("RPTDATE not between", value1, value2, "rptdate");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNull() {
            addCriterion("RECVERSION is null");
            return (Criteria) this;
        }

        public Criteria andRecversionIsNotNull() {
            addCriterion("RECVERSION is not null");
            return (Criteria) this;
        }

        public Criteria andRecversionEqualTo(Integer value) {
            addCriterion("RECVERSION =", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotEqualTo(Integer value) {
            addCriterion("RECVERSION <>", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThan(Integer value) {
            addCriterion("RECVERSION >", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionGreaterThanOrEqualTo(Integer value) {
            addCriterion("RECVERSION >=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThan(Integer value) {
            addCriterion("RECVERSION <", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionLessThanOrEqualTo(Integer value) {
            addCriterion("RECVERSION <=", value, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionIn(List<Integer> values) {
            addCriterion("RECVERSION in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotIn(List<Integer> values) {
            addCriterion("RECVERSION not in", values, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionBetween(Integer value1, Integer value2) {
            addCriterion("RECVERSION between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andRecversionNotBetween(Integer value1, Integer value2) {
            addCriterion("RECVERSION not between", value1, value2, "recversion");
            return (Criteria) this;
        }

        public Criteria andArchiveflagIsNull() {
            addCriterion("ARCHIVEFLAG is null");
            return (Criteria) this;
        }

        public Criteria andArchiveflagIsNotNull() {
            addCriterion("ARCHIVEFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveflagEqualTo(String value) {
            addCriterion("ARCHIVEFLAG =", value, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagNotEqualTo(String value) {
            addCriterion("ARCHIVEFLAG <>", value, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagGreaterThan(String value) {
            addCriterion("ARCHIVEFLAG >", value, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagGreaterThanOrEqualTo(String value) {
            addCriterion("ARCHIVEFLAG >=", value, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagLessThan(String value) {
            addCriterion("ARCHIVEFLAG <", value, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagLessThanOrEqualTo(String value) {
            addCriterion("ARCHIVEFLAG <=", value, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagLike(String value) {
            addCriterion("ARCHIVEFLAG like", value, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagNotLike(String value) {
            addCriterion("ARCHIVEFLAG not like", value, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagIn(List<String> values) {
            addCriterion("ARCHIVEFLAG in", values, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagNotIn(List<String> values) {
            addCriterion("ARCHIVEFLAG not in", values, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagBetween(String value1, String value2) {
            addCriterion("ARCHIVEFLAG between", value1, value2, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andArchiveflagNotBetween(String value1, String value2) {
            addCriterion("ARCHIVEFLAG not between", value1, value2, "archiveflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagIsNull() {
            addCriterion("DELETEDFLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeletedflagIsNotNull() {
            addCriterion("DELETEDFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedflagEqualTo(String value) {
            addCriterion("DELETEDFLAG =", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagNotEqualTo(String value) {
            addCriterion("DELETEDFLAG <>", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagGreaterThan(String value) {
            addCriterion("DELETEDFLAG >", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagGreaterThanOrEqualTo(String value) {
            addCriterion("DELETEDFLAG >=", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagLessThan(String value) {
            addCriterion("DELETEDFLAG <", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagLessThanOrEqualTo(String value) {
            addCriterion("DELETEDFLAG <=", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagLike(String value) {
            addCriterion("DELETEDFLAG like", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagNotLike(String value) {
            addCriterion("DELETEDFLAG not like", value, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagIn(List<String> values) {
            addCriterion("DELETEDFLAG in", values, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagNotIn(List<String> values) {
            addCriterion("DELETEDFLAG not in", values, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagBetween(String value1, String value2) {
            addCriterion("DELETEDFLAG between", value1, value2, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDeletedflagNotBetween(String value1, String value2) {
            addCriterion("DELETEDFLAG not between", value1, value2, "deletedflag");
            return (Criteria) this;
        }

        public Criteria andDateCreateIsNull() {
            addCriterion("DATE_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andDateCreateIsNotNull() {
            addCriterion("DATE_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreateEqualTo(Date value) {
            addCriterion("DATE_CREATE =", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotEqualTo(Date value) {
            addCriterion("DATE_CREATE <>", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateGreaterThan(Date value) {
            addCriterion("DATE_CREATE >", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_CREATE >=", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateLessThan(Date value) {
            addCriterion("DATE_CREATE <", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateLessThanOrEqualTo(Date value) {
            addCriterion("DATE_CREATE <=", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateIn(List<Date> values) {
            addCriterion("DATE_CREATE in", values, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotIn(List<Date> values) {
            addCriterion("DATE_CREATE not in", values, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateBetween(Date value1, Date value2) {
            addCriterion("DATE_CREATE between", value1, value2, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotBetween(Date value1, Date value2) {
            addCriterion("DATE_CREATE not between", value1, value2, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIsNull() {
            addCriterion("DATE_UPDATE is null");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIsNotNull() {
            addCriterion("DATE_UPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andDateUpdateEqualTo(Date value) {
            addCriterion("DATE_UPDATE =", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotEqualTo(Date value) {
            addCriterion("DATE_UPDATE <>", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateGreaterThan(Date value) {
            addCriterion("DATE_UPDATE >", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_UPDATE >=", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateLessThan(Date value) {
            addCriterion("DATE_UPDATE <", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateLessThanOrEqualTo(Date value) {
            addCriterion("DATE_UPDATE <=", value, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateIn(List<Date> values) {
            addCriterion("DATE_UPDATE in", values, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotIn(List<Date> values) {
            addCriterion("DATE_UPDATE not in", values, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateBetween(Date value1, Date value2) {
            addCriterion("DATE_UPDATE between", value1, value2, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateUpdateNotBetween(Date value1, Date value2) {
            addCriterion("DATE_UPDATE not between", value1, value2, "dateUpdate");
            return (Criteria) this;
        }

        public Criteria andDateDeleteIsNull() {
            addCriterion("DATE_DELETE is null");
            return (Criteria) this;
        }

        public Criteria andDateDeleteIsNotNull() {
            addCriterion("DATE_DELETE is not null");
            return (Criteria) this;
        }

        public Criteria andDateDeleteEqualTo(Date value) {
            addCriterion("DATE_DELETE =", value, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteNotEqualTo(Date value) {
            addCriterion("DATE_DELETE <>", value, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteGreaterThan(Date value) {
            addCriterion("DATE_DELETE >", value, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_DELETE >=", value, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteLessThan(Date value) {
            addCriterion("DATE_DELETE <", value, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteLessThanOrEqualTo(Date value) {
            addCriterion("DATE_DELETE <=", value, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteIn(List<Date> values) {
            addCriterion("DATE_DELETE in", values, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteNotIn(List<Date> values) {
            addCriterion("DATE_DELETE not in", values, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteBetween(Date value1, Date value2) {
            addCriterion("DATE_DELETE between", value1, value2, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateDeleteNotBetween(Date value1, Date value2) {
            addCriterion("DATE_DELETE not between", value1, value2, "dateDelete");
            return (Criteria) this;
        }

        public Criteria andDateArchiveIsNull() {
            addCriterion("DATE_ARCHIVE is null");
            return (Criteria) this;
        }

        public Criteria andDateArchiveIsNotNull() {
            addCriterion("DATE_ARCHIVE is not null");
            return (Criteria) this;
        }

        public Criteria andDateArchiveEqualTo(Date value) {
            addCriterion("DATE_ARCHIVE =", value, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveNotEqualTo(Date value) {
            addCriterion("DATE_ARCHIVE <>", value, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveGreaterThan(Date value) {
            addCriterion("DATE_ARCHIVE >", value, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_ARCHIVE >=", value, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveLessThan(Date value) {
            addCriterion("DATE_ARCHIVE <", value, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveLessThanOrEqualTo(Date value) {
            addCriterion("DATE_ARCHIVE <=", value, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveIn(List<Date> values) {
            addCriterion("DATE_ARCHIVE in", values, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveNotIn(List<Date> values) {
            addCriterion("DATE_ARCHIVE not in", values, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveBetween(Date value1, Date value2) {
            addCriterion("DATE_ARCHIVE between", value1, value2, "dateArchive");
            return (Criteria) this;
        }

        public Criteria andDateArchiveNotBetween(Date value1, Date value2) {
            addCriterion("DATE_ARCHIVE not between", value1, value2, "dateArchive");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 07 10:29:38 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.PBC_RATE_BALVERIFY
     *
     * @mbggenerated Wed Sep 07 10:29:38 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}