package haier.repository.model;

import java.math.BigDecimal;

public class PbcRateDepositbal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String reportdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String bankcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.CUSTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String custtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITACCOUNTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositaccountno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITAGREEMENTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositagreementno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String productstypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositstartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String depositenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String currencycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.BALAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal balamt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private String rateflexibletypecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal intrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMS.PBC_RATE_DEPOSITBAL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    private BigDecimal usdamt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.REPORTDATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getReportdate() {
        return reportdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.REPORTDATE
     *
     * @param reportdate the value for RMS.PBC_RATE_DEPOSITBAL.REPORTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setReportdate(String reportdate) {
        this.reportdate = reportdate == null ? null : reportdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.BANKCODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getBankcode() {
        return bankcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.BANKCODE
     *
     * @param bankcode the value for RMS.PBC_RATE_DEPOSITBAL.BANKCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setBankcode(String bankcode) {
        this.bankcode = bankcode == null ? null : bankcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.CUSTTYPE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.CUSTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getCusttype() {
        return custtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.CUSTTYPE
     *
     * @param custtype the value for RMS.PBC_RATE_DEPOSITBAL.CUSTTYPE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setCusttype(String custtype) {
        this.custtype = custtype == null ? null : custtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITACCOUNTNO
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.DEPOSITACCOUNTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositaccountno() {
        return depositaccountno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITACCOUNTNO
     *
     * @param depositaccountno the value for RMS.PBC_RATE_DEPOSITBAL.DEPOSITACCOUNTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositaccountno(String depositaccountno) {
        this.depositaccountno = depositaccountno == null ? null : depositaccountno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITAGREEMENTNO
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.DEPOSITAGREEMENTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositagreementno() {
        return depositagreementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITAGREEMENTNO
     *
     * @param depositagreementno the value for RMS.PBC_RATE_DEPOSITBAL.DEPOSITAGREEMENTNO
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositagreementno(String depositagreementno) {
        this.depositagreementno = depositagreementno == null ? null : depositagreementno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.PRODUCTSTYPECODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getProductstypecode() {
        return productstypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.PRODUCTSTYPECODE
     *
     * @param productstypecode the value for RMS.PBC_RATE_DEPOSITBAL.PRODUCTSTYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setProductstypecode(String productstypecode) {
        this.productstypecode = productstypecode == null ? null : productstypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITSTARTDATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.DEPOSITSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositstartdate() {
        return depositstartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITSTARTDATE
     *
     * @param depositstartdate the value for RMS.PBC_RATE_DEPOSITBAL.DEPOSITSTARTDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositstartdate(String depositstartdate) {
        this.depositstartdate = depositstartdate == null ? null : depositstartdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITENDDATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.DEPOSITENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getDepositenddate() {
        return depositenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.DEPOSITENDDATE
     *
     * @param depositenddate the value for RMS.PBC_RATE_DEPOSITBAL.DEPOSITENDDATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setDepositenddate(String depositenddate) {
        this.depositenddate = depositenddate == null ? null : depositenddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.CURRENCYCODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getCurrencycode() {
        return currencycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.CURRENCYCODE
     *
     * @param currencycode the value for RMS.PBC_RATE_DEPOSITBAL.CURRENCYCODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setCurrencycode(String currencycode) {
        this.currencycode = currencycode == null ? null : currencycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.BALAMT
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.BALAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getBalamt() {
        return balamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.BALAMT
     *
     * @param balamt the value for RMS.PBC_RATE_DEPOSITBAL.BALAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setBalamt(BigDecimal balamt) {
        this.balamt = balamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.RATEFLEXIBLETYPECODE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public String getRateflexibletypecode() {
        return rateflexibletypecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.RATEFLEXIBLETYPECODE
     *
     * @param rateflexibletypecode the value for RMS.PBC_RATE_DEPOSITBAL.RATEFLEXIBLETYPECODE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setRateflexibletypecode(String rateflexibletypecode) {
        this.rateflexibletypecode = rateflexibletypecode == null ? null : rateflexibletypecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.INTRATE
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getIntrate() {
        return intrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.INTRATE
     *
     * @param intrate the value for RMS.PBC_RATE_DEPOSITBAL.INTRATE
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setIntrate(BigDecimal intrate) {
        this.intrate = intrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMS.PBC_RATE_DEPOSITBAL.USDAMT
     *
     * @return the value of RMS.PBC_RATE_DEPOSITBAL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public BigDecimal getUsdamt() {
        return usdamt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMS.PBC_RATE_DEPOSITBAL.USDAMT
     *
     * @param usdamt the value for RMS.PBC_RATE_DEPOSITBAL.USDAMT
     *
     * @mbggenerated Fri Jan 18 12:06:34 CST 2013
     */
    public void setUsdamt(BigDecimal usdamt) {
        this.usdamt = usdamt;
    }
}