package haier.repository.model;

import java.util.ArrayList;
import java.util.List;

public class S1169CorplistExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public S1169CorplistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPkidIsNull() {
            addCriterion("PKID is null");
            return (Criteria) this;
        }

        public Criteria andPkidIsNotNull() {
            addCriterion("PKID is not null");
            return (Criteria) this;
        }

        public Criteria andPkidEqualTo(String value) {
            addCriterion("PKID =", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotEqualTo(String value) {
            addCriterion("PKID <>", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThan(String value) {
            addCriterion("PKID >", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidGreaterThanOrEqualTo(String value) {
            addCriterion("PKID >=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThan(String value) {
            addCriterion("PKID <", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLessThanOrEqualTo(String value) {
            addCriterion("PKID <=", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidLike(String value) {
            addCriterion("PKID like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotLike(String value) {
            addCriterion("PKID not like", value, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidIn(List<String> values) {
            addCriterion("PKID in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotIn(List<String> values) {
            addCriterion("PKID not in", values, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidBetween(String value1, String value2) {
            addCriterion("PKID between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andPkidNotBetween(String value1, String value2) {
            addCriterion("PKID not between", value1, value2, "pkid");
            return (Criteria) this;
        }

        public Criteria andCorpidIsNull() {
            addCriterion("CORPID is null");
            return (Criteria) this;
        }

        public Criteria andCorpidIsNotNull() {
            addCriterion("CORPID is not null");
            return (Criteria) this;
        }

        public Criteria andCorpidEqualTo(String value) {
            addCriterion("CORPID =", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotEqualTo(String value) {
            addCriterion("CORPID <>", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidGreaterThan(String value) {
            addCriterion("CORPID >", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidGreaterThanOrEqualTo(String value) {
            addCriterion("CORPID >=", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidLessThan(String value) {
            addCriterion("CORPID <", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidLessThanOrEqualTo(String value) {
            addCriterion("CORPID <=", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidLike(String value) {
            addCriterion("CORPID like", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotLike(String value) {
            addCriterion("CORPID not like", value, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidIn(List<String> values) {
            addCriterion("CORPID in", values, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotIn(List<String> values) {
            addCriterion("CORPID not in", values, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidBetween(String value1, String value2) {
            addCriterion("CORPID between", value1, value2, "corpid");
            return (Criteria) this;
        }

        public Criteria andCorpidNotBetween(String value1, String value2) {
            addCriterion("CORPID not between", value1, value2, "corpid");
            return (Criteria) this;
        }

        public Criteria andCordnameIsNull() {
            addCriterion("CORDNAME is null");
            return (Criteria) this;
        }

        public Criteria andCordnameIsNotNull() {
            addCriterion("CORDNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCordnameEqualTo(String value) {
            addCriterion("CORDNAME =", value, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameNotEqualTo(String value) {
            addCriterion("CORDNAME <>", value, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameGreaterThan(String value) {
            addCriterion("CORDNAME >", value, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameGreaterThanOrEqualTo(String value) {
            addCriterion("CORDNAME >=", value, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameLessThan(String value) {
            addCriterion("CORDNAME <", value, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameLessThanOrEqualTo(String value) {
            addCriterion("CORDNAME <=", value, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameLike(String value) {
            addCriterion("CORDNAME like", value, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameNotLike(String value) {
            addCriterion("CORDNAME not like", value, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameIn(List<String> values) {
            addCriterion("CORDNAME in", values, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameNotIn(List<String> values) {
            addCriterion("CORDNAME not in", values, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameBetween(String value1, String value2) {
            addCriterion("CORDNAME between", value1, value2, "cordname");
            return (Criteria) this;
        }

        public Criteria andCordnameNotBetween(String value1, String value2) {
            addCriterion("CORDNAME not between", value1, value2, "cordname");
            return (Criteria) this;
        }

        public Criteria andCorpcodeIsNull() {
            addCriterion("CORPCODE is null");
            return (Criteria) this;
        }

        public Criteria andCorpcodeIsNotNull() {
            addCriterion("CORPCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCorpcodeEqualTo(String value) {
            addCriterion("CORPCODE =", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotEqualTo(String value) {
            addCriterion("CORPCODE <>", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeGreaterThan(String value) {
            addCriterion("CORPCODE >", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CORPCODE >=", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLessThan(String value) {
            addCriterion("CORPCODE <", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLessThanOrEqualTo(String value) {
            addCriterion("CORPCODE <=", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeLike(String value) {
            addCriterion("CORPCODE like", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotLike(String value) {
            addCriterion("CORPCODE not like", value, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeIn(List<String> values) {
            addCriterion("CORPCODE in", values, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotIn(List<String> values) {
            addCriterion("CORPCODE not in", values, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeBetween(String value1, String value2) {
            addCriterion("CORPCODE between", value1, value2, "corpcode");
            return (Criteria) this;
        }

        public Criteria andCorpcodeNotBetween(String value1, String value2) {
            addCriterion("CORPCODE not between", value1, value2, "corpcode");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNull() {
            addCriterion("SEQNO is null");
            return (Criteria) this;
        }

        public Criteria andSeqnoIsNotNull() {
            addCriterion("SEQNO is not null");
            return (Criteria) this;
        }

        public Criteria andSeqnoEqualTo(String value) {
            addCriterion("SEQNO =", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotEqualTo(String value) {
            addCriterion("SEQNO <>", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThan(String value) {
            addCriterion("SEQNO >", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoGreaterThanOrEqualTo(String value) {
            addCriterion("SEQNO >=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThan(String value) {
            addCriterion("SEQNO <", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLessThanOrEqualTo(String value) {
            addCriterion("SEQNO <=", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoLike(String value) {
            addCriterion("SEQNO like", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotLike(String value) {
            addCriterion("SEQNO not like", value, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoIn(List<String> values) {
            addCriterion("SEQNO in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotIn(List<String> values) {
            addCriterion("SEQNO not in", values, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoBetween(String value1, String value2) {
            addCriterion("SEQNO between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andSeqnoNotBetween(String value1, String value2) {
            addCriterion("SEQNO not between", value1, value2, "seqno");
            return (Criteria) this;
        }

        public Criteria andChkoperidIsNull() {
            addCriterion("CHKOPERID is null");
            return (Criteria) this;
        }

        public Criteria andChkoperidIsNotNull() {
            addCriterion("CHKOPERID is not null");
            return (Criteria) this;
        }

        public Criteria andChkoperidEqualTo(String value) {
            addCriterion("CHKOPERID =", value, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidNotEqualTo(String value) {
            addCriterion("CHKOPERID <>", value, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidGreaterThan(String value) {
            addCriterion("CHKOPERID >", value, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidGreaterThanOrEqualTo(String value) {
            addCriterion("CHKOPERID >=", value, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidLessThan(String value) {
            addCriterion("CHKOPERID <", value, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidLessThanOrEqualTo(String value) {
            addCriterion("CHKOPERID <=", value, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidLike(String value) {
            addCriterion("CHKOPERID like", value, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidNotLike(String value) {
            addCriterion("CHKOPERID not like", value, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidIn(List<String> values) {
            addCriterion("CHKOPERID in", values, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidNotIn(List<String> values) {
            addCriterion("CHKOPERID not in", values, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidBetween(String value1, String value2) {
            addCriterion("CHKOPERID between", value1, value2, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkoperidNotBetween(String value1, String value2) {
            addCriterion("CHKOPERID not between", value1, value2, "chkoperid");
            return (Criteria) this;
        }

        public Criteria andChkopernameIsNull() {
            addCriterion("CHKOPERNAME is null");
            return (Criteria) this;
        }

        public Criteria andChkopernameIsNotNull() {
            addCriterion("CHKOPERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andChkopernameEqualTo(String value) {
            addCriterion("CHKOPERNAME =", value, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameNotEqualTo(String value) {
            addCriterion("CHKOPERNAME <>", value, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameGreaterThan(String value) {
            addCriterion("CHKOPERNAME >", value, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameGreaterThanOrEqualTo(String value) {
            addCriterion("CHKOPERNAME >=", value, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameLessThan(String value) {
            addCriterion("CHKOPERNAME <", value, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameLessThanOrEqualTo(String value) {
            addCriterion("CHKOPERNAME <=", value, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameLike(String value) {
            addCriterion("CHKOPERNAME like", value, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameNotLike(String value) {
            addCriterion("CHKOPERNAME not like", value, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameIn(List<String> values) {
            addCriterion("CHKOPERNAME in", values, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameNotIn(List<String> values) {
            addCriterion("CHKOPERNAME not in", values, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameBetween(String value1, String value2) {
            addCriterion("CHKOPERNAME between", value1, value2, "chkopername");
            return (Criteria) this;
        }

        public Criteria andChkopernameNotBetween(String value1, String value2) {
            addCriterion("CHKOPERNAME not between", value1, value2, "chkopername");
            return (Criteria) this;
        }

        public Criteria andOperidIsNull() {
            addCriterion("OPERID is null");
            return (Criteria) this;
        }

        public Criteria andOperidIsNotNull() {
            addCriterion("OPERID is not null");
            return (Criteria) this;
        }

        public Criteria andOperidEqualTo(String value) {
            addCriterion("OPERID =", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotEqualTo(String value) {
            addCriterion("OPERID <>", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThan(String value) {
            addCriterion("OPERID >", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidGreaterThanOrEqualTo(String value) {
            addCriterion("OPERID >=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThan(String value) {
            addCriterion("OPERID <", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLessThanOrEqualTo(String value) {
            addCriterion("OPERID <=", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidLike(String value) {
            addCriterion("OPERID like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotLike(String value) {
            addCriterion("OPERID not like", value, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidIn(List<String> values) {
            addCriterion("OPERID in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotIn(List<String> values) {
            addCriterion("OPERID not in", values, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidBetween(String value1, String value2) {
            addCriterion("OPERID between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOperidNotBetween(String value1, String value2) {
            addCriterion("OPERID not between", value1, value2, "operid");
            return (Criteria) this;
        }

        public Criteria andOpernameIsNull() {
            addCriterion("OPERNAME is null");
            return (Criteria) this;
        }

        public Criteria andOpernameIsNotNull() {
            addCriterion("OPERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andOpernameEqualTo(String value) {
            addCriterion("OPERNAME =", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotEqualTo(String value) {
            addCriterion("OPERNAME <>", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameGreaterThan(String value) {
            addCriterion("OPERNAME >", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameGreaterThanOrEqualTo(String value) {
            addCriterion("OPERNAME >=", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLessThan(String value) {
            addCriterion("OPERNAME <", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLessThanOrEqualTo(String value) {
            addCriterion("OPERNAME <=", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameLike(String value) {
            addCriterion("OPERNAME like", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotLike(String value) {
            addCriterion("OPERNAME not like", value, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameIn(List<String> values) {
            addCriterion("OPERNAME in", values, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotIn(List<String> values) {
            addCriterion("OPERNAME not in", values, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameBetween(String value1, String value2) {
            addCriterion("OPERNAME between", value1, value2, "opername");
            return (Criteria) this;
        }

        public Criteria andOpernameNotBetween(String value1, String value2) {
            addCriterion("OPERNAME not between", value1, value2, "opername");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 07 14:33:52 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table RMS.S1169_CORPLIST
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}