package haier.repository.model;

public class S1169ActtypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S1169_ACTTYPE.BANKCD
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    private String bankcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S1169_ACTTYPE.ACTNO
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    private String actno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S1169_ACTTYPE.BANKCD
     *
     * @return the value of S1169_ACTTYPE.BANKCD
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public String getBankcd() {
        return bankcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S1169_ACTTYPE.BANKCD
     *
     * @param bankcd the value for S1169_ACTTYPE.BANKCD
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void setBankcd(String bankcd) {
        this.bankcd = bankcd == null ? null : bankcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S1169_ACTTYPE.ACTNO
     *
     * @return the value of S1169_ACTTYPE.ACTNO
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public String getActno() {
        return actno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S1169_ACTTYPE.ACTNO
     *
     * @param actno the value for S1169_ACTTYPE.ACTNO
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void setActno(String actno) {
        this.actno = actno == null ? null : actno.trim();
    }
}