package haier.repository.model;

import java.util.ArrayList;
import java.util.List;

public class S1169ActtypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public S1169ActtypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBankcdIsNull() {
            addCriterion("BANKCD is null");
            return (Criteria) this;
        }

        public Criteria andBankcdIsNotNull() {
            addCriterion("BANKCD is not null");
            return (Criteria) this;
        }

        public Criteria andBankcdEqualTo(String value) {
            addCriterion("BANKCD =", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdNotEqualTo(String value) {
            addCriterion("BANKCD <>", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdGreaterThan(String value) {
            addCriterion("BANKCD >", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdGreaterThanOrEqualTo(String value) {
            addCriterion("BANKCD >=", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdLessThan(String value) {
            addCriterion("BANKCD <", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdLessThanOrEqualTo(String value) {
            addCriterion("BANKCD <=", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdLike(String value) {
            addCriterion("BANKCD like", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdNotLike(String value) {
            addCriterion("BANKCD not like", value, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdIn(List<String> values) {
            addCriterion("BANKCD in", values, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdNotIn(List<String> values) {
            addCriterion("BANKCD not in", values, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdBetween(String value1, String value2) {
            addCriterion("BANKCD between", value1, value2, "bankcd");
            return (Criteria) this;
        }

        public Criteria andBankcdNotBetween(String value1, String value2) {
            addCriterion("BANKCD not between", value1, value2, "bankcd");
            return (Criteria) this;
        }

        public Criteria andActnoIsNull() {
            addCriterion("ACTNO is null");
            return (Criteria) this;
        }

        public Criteria andActnoIsNotNull() {
            addCriterion("ACTNO is not null");
            return (Criteria) this;
        }

        public Criteria andActnoEqualTo(String value) {
            addCriterion("ACTNO =", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotEqualTo(String value) {
            addCriterion("ACTNO <>", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoGreaterThan(String value) {
            addCriterion("ACTNO >", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoGreaterThanOrEqualTo(String value) {
            addCriterion("ACTNO >=", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLessThan(String value) {
            addCriterion("ACTNO <", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLessThanOrEqualTo(String value) {
            addCriterion("ACTNO <=", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoLike(String value) {
            addCriterion("ACTNO like", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotLike(String value) {
            addCriterion("ACTNO not like", value, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoIn(List<String> values) {
            addCriterion("ACTNO in", values, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotIn(List<String> values) {
            addCriterion("ACTNO not in", values, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoBetween(String value1, String value2) {
            addCriterion("ACTNO between", value1, value2, "actno");
            return (Criteria) this;
        }

        public Criteria andActnoNotBetween(String value1, String value2) {
            addCriterion("ACTNO not between", value1, value2, "actno");
            return (Criteria) this;
        }

        public Criteria andActnameIsNull() {
            addCriterion("ACTNAME is null");
            return (Criteria) this;
        }

        public Criteria andActnameIsNotNull() {
            addCriterion("ACTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andActnameEqualTo(String value) {
            addCriterion("ACTNAME =", value, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameNotEqualTo(String value) {
            addCriterion("ACTNAME <>", value, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameGreaterThan(String value) {
            addCriterion("ACTNAME >", value, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameGreaterThanOrEqualTo(String value) {
            addCriterion("ACTNAME >=", value, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameLessThan(String value) {
            addCriterion("ACTNAME <", value, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameLessThanOrEqualTo(String value) {
            addCriterion("ACTNAME <=", value, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameLike(String value) {
            addCriterion("ACTNAME like", value, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameNotLike(String value) {
            addCriterion("ACTNAME not like", value, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameIn(List<String> values) {
            addCriterion("ACTNAME in", values, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameNotIn(List<String> values) {
            addCriterion("ACTNAME not in", values, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameBetween(String value1, String value2) {
            addCriterion("ACTNAME between", value1, value2, "actname");
            return (Criteria) this;
        }

        public Criteria andActnameNotBetween(String value1, String value2) {
            addCriterion("ACTNAME not between", value1, value2, "actname");
            return (Criteria) this;
        }

        public Criteria andOpeningbankIsNull() {
            addCriterion("OPENINGBANK is null");
            return (Criteria) this;
        }

        public Criteria andOpeningbankIsNotNull() {
            addCriterion("OPENINGBANK is not null");
            return (Criteria) this;
        }

        public Criteria andOpeningbankEqualTo(String value) {
            addCriterion("OPENINGBANK =", value, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankNotEqualTo(String value) {
            addCriterion("OPENINGBANK <>", value, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankGreaterThan(String value) {
            addCriterion("OPENINGBANK >", value, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankGreaterThanOrEqualTo(String value) {
            addCriterion("OPENINGBANK >=", value, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankLessThan(String value) {
            addCriterion("OPENINGBANK <", value, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankLessThanOrEqualTo(String value) {
            addCriterion("OPENINGBANK <=", value, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankLike(String value) {
            addCriterion("OPENINGBANK like", value, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankNotLike(String value) {
            addCriterion("OPENINGBANK not like", value, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankIn(List<String> values) {
            addCriterion("OPENINGBANK in", values, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankNotIn(List<String> values) {
            addCriterion("OPENINGBANK not in", values, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankBetween(String value1, String value2) {
            addCriterion("OPENINGBANK between", value1, value2, "openingbank");
            return (Criteria) this;
        }

        public Criteria andOpeningbankNotBetween(String value1, String value2) {
            addCriterion("OPENINGBANK not between", value1, value2, "openingbank");
            return (Criteria) this;
        }

        public Criteria andActattrIsNull() {
            addCriterion("ACTATTR is null");
            return (Criteria) this;
        }

        public Criteria andActattrIsNotNull() {
            addCriterion("ACTATTR is not null");
            return (Criteria) this;
        }

        public Criteria andActattrEqualTo(String value) {
            addCriterion("ACTATTR =", value, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrNotEqualTo(String value) {
            addCriterion("ACTATTR <>", value, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrGreaterThan(String value) {
            addCriterion("ACTATTR >", value, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrGreaterThanOrEqualTo(String value) {
            addCriterion("ACTATTR >=", value, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrLessThan(String value) {
            addCriterion("ACTATTR <", value, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrLessThanOrEqualTo(String value) {
            addCriterion("ACTATTR <=", value, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrLike(String value) {
            addCriterion("ACTATTR like", value, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrNotLike(String value) {
            addCriterion("ACTATTR not like", value, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrIn(List<String> values) {
            addCriterion("ACTATTR in", values, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrNotIn(List<String> values) {
            addCriterion("ACTATTR not in", values, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrBetween(String value1, String value2) {
            addCriterion("ACTATTR between", value1, value2, "actattr");
            return (Criteria) this;
        }

        public Criteria andActattrNotBetween(String value1, String value2) {
            addCriterion("ACTATTR not between", value1, value2, "actattr");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNull() {
            addCriterion("DEPTID is null");
            return (Criteria) this;
        }

        public Criteria andDeptidIsNotNull() {
            addCriterion("DEPTID is not null");
            return (Criteria) this;
        }

        public Criteria andDeptidEqualTo(String value) {
            addCriterion("DEPTID =", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotEqualTo(String value) {
            addCriterion("DEPTID <>", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThan(String value) {
            addCriterion("DEPTID >", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTID >=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThan(String value) {
            addCriterion("DEPTID <", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLessThanOrEqualTo(String value) {
            addCriterion("DEPTID <=", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidLike(String value) {
            addCriterion("DEPTID like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotLike(String value) {
            addCriterion("DEPTID not like", value, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidIn(List<String> values) {
            addCriterion("DEPTID in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotIn(List<String> values) {
            addCriterion("DEPTID not in", values, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidBetween(String value1, String value2) {
            addCriterion("DEPTID between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptidNotBetween(String value1, String value2) {
            addCriterion("DEPTID not between", value1, value2, "deptid");
            return (Criteria) this;
        }

        public Criteria andDeptnameIsNull() {
            addCriterion("DEPTNAME is null");
            return (Criteria) this;
        }

        public Criteria andDeptnameIsNotNull() {
            addCriterion("DEPTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDeptnameEqualTo(String value) {
            addCriterion("DEPTNAME =", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameNotEqualTo(String value) {
            addCriterion("DEPTNAME <>", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameGreaterThan(String value) {
            addCriterion("DEPTNAME >", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameGreaterThanOrEqualTo(String value) {
            addCriterion("DEPTNAME >=", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameLessThan(String value) {
            addCriterion("DEPTNAME <", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameLessThanOrEqualTo(String value) {
            addCriterion("DEPTNAME <=", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameLike(String value) {
            addCriterion("DEPTNAME like", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameNotLike(String value) {
            addCriterion("DEPTNAME not like", value, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameIn(List<String> values) {
            addCriterion("DEPTNAME in", values, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameNotIn(List<String> values) {
            addCriterion("DEPTNAME not in", values, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameBetween(String value1, String value2) {
            addCriterion("DEPTNAME between", value1, value2, "deptname");
            return (Criteria) this;
        }

        public Criteria andDeptnameNotBetween(String value1, String value2) {
            addCriterion("DEPTNAME not between", value1, value2, "deptname");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNull() {
            addCriterion("CURCDE is null");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNotNull() {
            addCriterion("CURCDE is not null");
            return (Criteria) this;
        }

        public Criteria andCurcdeEqualTo(String value) {
            addCriterion("CURCDE =", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotEqualTo(String value) {
            addCriterion("CURCDE <>", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThan(String value) {
            addCriterion("CURCDE >", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThanOrEqualTo(String value) {
            addCriterion("CURCDE >=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThan(String value) {
            addCriterion("CURCDE <", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThanOrEqualTo(String value) {
            addCriterion("CURCDE <=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLike(String value) {
            addCriterion("CURCDE like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotLike(String value) {
            addCriterion("CURCDE not like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeIn(List<String> values) {
            addCriterion("CURCDE in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotIn(List<String> values) {
            addCriterion("CURCDE not in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeBetween(String value1, String value2) {
            addCriterion("CURCDE between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotBetween(String value1, String value2) {
            addCriterion("CURCDE not between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurnameIsNull() {
            addCriterion("CURNAME is null");
            return (Criteria) this;
        }

        public Criteria andCurnameIsNotNull() {
            addCriterion("CURNAME is not null");
            return (Criteria) this;
        }

        public Criteria andCurnameEqualTo(String value) {
            addCriterion("CURNAME =", value, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameNotEqualTo(String value) {
            addCriterion("CURNAME <>", value, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameGreaterThan(String value) {
            addCriterion("CURNAME >", value, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameGreaterThanOrEqualTo(String value) {
            addCriterion("CURNAME >=", value, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameLessThan(String value) {
            addCriterion("CURNAME <", value, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameLessThanOrEqualTo(String value) {
            addCriterion("CURNAME <=", value, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameLike(String value) {
            addCriterion("CURNAME like", value, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameNotLike(String value) {
            addCriterion("CURNAME not like", value, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameIn(List<String> values) {
            addCriterion("CURNAME in", values, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameNotIn(List<String> values) {
            addCriterion("CURNAME not in", values, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameBetween(String value1, String value2) {
            addCriterion("CURNAME between", value1, value2, "curname");
            return (Criteria) this;
        }

        public Criteria andCurnameNotBetween(String value1, String value2) {
            addCriterion("CURNAME not between", value1, value2, "curname");
            return (Criteria) this;
        }

        public Criteria andActstsIsNull() {
            addCriterion("ACTSTS is null");
            return (Criteria) this;
        }

        public Criteria andActstsIsNotNull() {
            addCriterion("ACTSTS is not null");
            return (Criteria) this;
        }

        public Criteria andActstsEqualTo(String value) {
            addCriterion("ACTSTS =", value, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsNotEqualTo(String value) {
            addCriterion("ACTSTS <>", value, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsGreaterThan(String value) {
            addCriterion("ACTSTS >", value, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsGreaterThanOrEqualTo(String value) {
            addCriterion("ACTSTS >=", value, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsLessThan(String value) {
            addCriterion("ACTSTS <", value, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsLessThanOrEqualTo(String value) {
            addCriterion("ACTSTS <=", value, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsLike(String value) {
            addCriterion("ACTSTS like", value, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsNotLike(String value) {
            addCriterion("ACTSTS not like", value, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsIn(List<String> values) {
            addCriterion("ACTSTS in", values, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsNotIn(List<String> values) {
            addCriterion("ACTSTS not in", values, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsBetween(String value1, String value2) {
            addCriterion("ACTSTS between", value1, value2, "actsts");
            return (Criteria) this;
        }

        public Criteria andActstsNotBetween(String value1, String value2) {
            addCriterion("ACTSTS not between", value1, value2, "actsts");
            return (Criteria) this;
        }

        public Criteria andBankitemIsNull() {
            addCriterion("BANKITEM is null");
            return (Criteria) this;
        }

        public Criteria andBankitemIsNotNull() {
            addCriterion("BANKITEM is not null");
            return (Criteria) this;
        }

        public Criteria andBankitemEqualTo(String value) {
            addCriterion("BANKITEM =", value, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemNotEqualTo(String value) {
            addCriterion("BANKITEM <>", value, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemGreaterThan(String value) {
            addCriterion("BANKITEM >", value, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemGreaterThanOrEqualTo(String value) {
            addCriterion("BANKITEM >=", value, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemLessThan(String value) {
            addCriterion("BANKITEM <", value, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemLessThanOrEqualTo(String value) {
            addCriterion("BANKITEM <=", value, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemLike(String value) {
            addCriterion("BANKITEM like", value, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemNotLike(String value) {
            addCriterion("BANKITEM not like", value, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemIn(List<String> values) {
            addCriterion("BANKITEM in", values, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemNotIn(List<String> values) {
            addCriterion("BANKITEM not in", values, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemBetween(String value1, String value2) {
            addCriterion("BANKITEM between", value1, value2, "bankitem");
            return (Criteria) this;
        }

        public Criteria andBankitemNotBetween(String value1, String value2) {
            addCriterion("BANKITEM not between", value1, value2, "bankitem");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNull() {
            addCriterion("ITEMNAME is null");
            return (Criteria) this;
        }

        public Criteria andItemnameIsNotNull() {
            addCriterion("ITEMNAME is not null");
            return (Criteria) this;
        }

        public Criteria andItemnameEqualTo(String value) {
            addCriterion("ITEMNAME =", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotEqualTo(String value) {
            addCriterion("ITEMNAME <>", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThan(String value) {
            addCriterion("ITEMNAME >", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameGreaterThanOrEqualTo(String value) {
            addCriterion("ITEMNAME >=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThan(String value) {
            addCriterion("ITEMNAME <", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLessThanOrEqualTo(String value) {
            addCriterion("ITEMNAME <=", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameLike(String value) {
            addCriterion("ITEMNAME like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotLike(String value) {
            addCriterion("ITEMNAME not like", value, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameIn(List<String> values) {
            addCriterion("ITEMNAME in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotIn(List<String> values) {
            addCriterion("ITEMNAME not in", values, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameBetween(String value1, String value2) {
            addCriterion("ITEMNAME between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andItemnameNotBetween(String value1, String value2) {
            addCriterion("ITEMNAME not between", value1, value2, "itemname");
            return (Criteria) this;
        }

        public Criteria andOpendateIsNull() {
            addCriterion("OPENDATE is null");
            return (Criteria) this;
        }

        public Criteria andOpendateIsNotNull() {
            addCriterion("OPENDATE is not null");
            return (Criteria) this;
        }

        public Criteria andOpendateEqualTo(String value) {
            addCriterion("OPENDATE =", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateNotEqualTo(String value) {
            addCriterion("OPENDATE <>", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateGreaterThan(String value) {
            addCriterion("OPENDATE >", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateGreaterThanOrEqualTo(String value) {
            addCriterion("OPENDATE >=", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateLessThan(String value) {
            addCriterion("OPENDATE <", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateLessThanOrEqualTo(String value) {
            addCriterion("OPENDATE <=", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateLike(String value) {
            addCriterion("OPENDATE like", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateNotLike(String value) {
            addCriterion("OPENDATE not like", value, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateIn(List<String> values) {
            addCriterion("OPENDATE in", values, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateNotIn(List<String> values) {
            addCriterion("OPENDATE not in", values, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateBetween(String value1, String value2) {
            addCriterion("OPENDATE between", value1, value2, "opendate");
            return (Criteria) this;
        }

        public Criteria andOpendateNotBetween(String value1, String value2) {
            addCriterion("OPENDATE not between", value1, value2, "opendate");
            return (Criteria) this;
        }

        public Criteria andClosedateIsNull() {
            addCriterion("CLOSEDATE is null");
            return (Criteria) this;
        }

        public Criteria andClosedateIsNotNull() {
            addCriterion("CLOSEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andClosedateEqualTo(String value) {
            addCriterion("CLOSEDATE =", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotEqualTo(String value) {
            addCriterion("CLOSEDATE <>", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateGreaterThan(String value) {
            addCriterion("CLOSEDATE >", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateGreaterThanOrEqualTo(String value) {
            addCriterion("CLOSEDATE >=", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateLessThan(String value) {
            addCriterion("CLOSEDATE <", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateLessThanOrEqualTo(String value) {
            addCriterion("CLOSEDATE <=", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateLike(String value) {
            addCriterion("CLOSEDATE like", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotLike(String value) {
            addCriterion("CLOSEDATE not like", value, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateIn(List<String> values) {
            addCriterion("CLOSEDATE in", values, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotIn(List<String> values) {
            addCriterion("CLOSEDATE not in", values, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateBetween(String value1, String value2) {
            addCriterion("CLOSEDATE between", value1, value2, "closedate");
            return (Criteria) this;
        }

        public Criteria andClosedateNotBetween(String value1, String value2) {
            addCriterion("CLOSEDATE not between", value1, value2, "closedate");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 07 14:33:52 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table S1169_ACTTYPE
     *
     * @mbggenerated Thu Mar 07 14:33:52 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}