package haier.repository.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SbsActccyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public SbsActccyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCurcdeIsNull() {
            addCriterion("CURCDE is null");
            return (Criteria) this;
        }

        public Criteria andCurcdeIsNotNull() {
            addCriterion("CURCDE is not null");
            return (Criteria) this;
        }

        public Criteria andCurcdeEqualTo(String value) {
            addCriterion("CURCDE =", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotEqualTo(String value) {
            addCriterion("CURCDE <>", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThan(String value) {
            addCriterion("CURCDE >", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeGreaterThanOrEqualTo(String value) {
            addCriterion("CURCDE >=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThan(String value) {
            addCriterion("CURCDE <", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLessThanOrEqualTo(String value) {
            addCriterion("CURCDE <=", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeLike(String value) {
            addCriterion("CURCDE like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotLike(String value) {
            addCriterion("CURCDE not like", value, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeIn(List<String> values) {
            addCriterion("CURCDE in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotIn(List<String> values) {
            addCriterion("CURCDE not in", values, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeBetween(String value1, String value2) {
            addCriterion("CURCDE between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurcdeNotBetween(String value1, String value2) {
            addCriterion("CURCDE not between", value1, value2, "curcde");
            return (Criteria) this;
        }

        public Criteria andCurnmcIsNull() {
            addCriterion("CURNMC is null");
            return (Criteria) this;
        }

        public Criteria andCurnmcIsNotNull() {
            addCriterion("CURNMC is not null");
            return (Criteria) this;
        }

        public Criteria andCurnmcEqualTo(String value) {
            addCriterion("CURNMC =", value, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcNotEqualTo(String value) {
            addCriterion("CURNMC <>", value, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcGreaterThan(String value) {
            addCriterion("CURNMC >", value, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcGreaterThanOrEqualTo(String value) {
            addCriterion("CURNMC >=", value, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcLessThan(String value) {
            addCriterion("CURNMC <", value, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcLessThanOrEqualTo(String value) {
            addCriterion("CURNMC <=", value, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcLike(String value) {
            addCriterion("CURNMC like", value, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcNotLike(String value) {
            addCriterion("CURNMC not like", value, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcIn(List<String> values) {
            addCriterion("CURNMC in", values, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcNotIn(List<String> values) {
            addCriterion("CURNMC not in", values, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcBetween(String value1, String value2) {
            addCriterion("CURNMC between", value1, value2, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmcNotBetween(String value1, String value2) {
            addCriterion("CURNMC not between", value1, value2, "curnmc");
            return (Criteria) this;
        }

        public Criteria andCurnmeIsNull() {
            addCriterion("CURNME is null");
            return (Criteria) this;
        }

        public Criteria andCurnmeIsNotNull() {
            addCriterion("CURNME is not null");
            return (Criteria) this;
        }

        public Criteria andCurnmeEqualTo(String value) {
            addCriterion("CURNME =", value, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeNotEqualTo(String value) {
            addCriterion("CURNME <>", value, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeGreaterThan(String value) {
            addCriterion("CURNME >", value, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeGreaterThanOrEqualTo(String value) {
            addCriterion("CURNME >=", value, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeLessThan(String value) {
            addCriterion("CURNME <", value, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeLessThanOrEqualTo(String value) {
            addCriterion("CURNME <=", value, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeLike(String value) {
            addCriterion("CURNME like", value, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeNotLike(String value) {
            addCriterion("CURNME not like", value, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeIn(List<String> values) {
            addCriterion("CURNME in", values, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeNotIn(List<String> values) {
            addCriterion("CURNME not in", values, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeBetween(String value1, String value2) {
            addCriterion("CURNME between", value1, value2, "curnme");
            return (Criteria) this;
        }

        public Criteria andCurnmeNotBetween(String value1, String value2) {
            addCriterion("CURNME not between", value1, value2, "curnme");
            return (Criteria) this;
        }

        public Criteria andDomcdeIsNull() {
            addCriterion("DOMCDE is null");
            return (Criteria) this;
        }

        public Criteria andDomcdeIsNotNull() {
            addCriterion("DOMCDE is not null");
            return (Criteria) this;
        }

        public Criteria andDomcdeEqualTo(String value) {
            addCriterion("DOMCDE =", value, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeNotEqualTo(String value) {
            addCriterion("DOMCDE <>", value, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeGreaterThan(String value) {
            addCriterion("DOMCDE >", value, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeGreaterThanOrEqualTo(String value) {
            addCriterion("DOMCDE >=", value, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeLessThan(String value) {
            addCriterion("DOMCDE <", value, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeLessThanOrEqualTo(String value) {
            addCriterion("DOMCDE <=", value, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeLike(String value) {
            addCriterion("DOMCDE like", value, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeNotLike(String value) {
            addCriterion("DOMCDE not like", value, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeIn(List<String> values) {
            addCriterion("DOMCDE in", values, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeNotIn(List<String> values) {
            addCriterion("DOMCDE not in", values, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeBetween(String value1, String value2) {
            addCriterion("DOMCDE between", value1, value2, "domcde");
            return (Criteria) this;
        }

        public Criteria andDomcdeNotBetween(String value1, String value2) {
            addCriterion("DOMCDE not between", value1, value2, "domcde");
            return (Criteria) this;
        }

        public Criteria andIntcurIsNull() {
            addCriterion("INTCUR is null");
            return (Criteria) this;
        }

        public Criteria andIntcurIsNotNull() {
            addCriterion("INTCUR is not null");
            return (Criteria) this;
        }

        public Criteria andIntcurEqualTo(String value) {
            addCriterion("INTCUR =", value, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurNotEqualTo(String value) {
            addCriterion("INTCUR <>", value, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurGreaterThan(String value) {
            addCriterion("INTCUR >", value, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurGreaterThanOrEqualTo(String value) {
            addCriterion("INTCUR >=", value, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurLessThan(String value) {
            addCriterion("INTCUR <", value, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurLessThanOrEqualTo(String value) {
            addCriterion("INTCUR <=", value, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurLike(String value) {
            addCriterion("INTCUR like", value, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurNotLike(String value) {
            addCriterion("INTCUR not like", value, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurIn(List<String> values) {
            addCriterion("INTCUR in", values, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurNotIn(List<String> values) {
            addCriterion("INTCUR not in", values, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurBetween(String value1, String value2) {
            addCriterion("INTCUR between", value1, value2, "intcur");
            return (Criteria) this;
        }

        public Criteria andIntcurNotBetween(String value1, String value2) {
            addCriterion("INTCUR not between", value1, value2, "intcur");
            return (Criteria) this;
        }

        public Criteria andCuruntIsNull() {
            addCriterion("CURUNT is null");
            return (Criteria) this;
        }

        public Criteria andCuruntIsNotNull() {
            addCriterion("CURUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCuruntEqualTo(Integer value) {
            addCriterion("CURUNT =", value, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntNotEqualTo(Integer value) {
            addCriterion("CURUNT <>", value, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntGreaterThan(Integer value) {
            addCriterion("CURUNT >", value, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntGreaterThanOrEqualTo(Integer value) {
            addCriterion("CURUNT >=", value, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntLessThan(Integer value) {
            addCriterion("CURUNT <", value, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntLessThanOrEqualTo(Integer value) {
            addCriterion("CURUNT <=", value, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntIn(List<Integer> values) {
            addCriterion("CURUNT in", values, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntNotIn(List<Integer> values) {
            addCriterion("CURUNT not in", values, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntBetween(Integer value1, Integer value2) {
            addCriterion("CURUNT between", value1, value2, "curunt");
            return (Criteria) this;
        }

        public Criteria andCuruntNotBetween(Integer value1, Integer value2) {
            addCriterion("CURUNT not between", value1, value2, "curunt");
            return (Criteria) this;
        }

        public Criteria andDecposIsNull() {
            addCriterion("DECPOS is null");
            return (Criteria) this;
        }

        public Criteria andDecposIsNotNull() {
            addCriterion("DECPOS is not null");
            return (Criteria) this;
        }

        public Criteria andDecposEqualTo(Short value) {
            addCriterion("DECPOS =", value, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposNotEqualTo(Short value) {
            addCriterion("DECPOS <>", value, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposGreaterThan(Short value) {
            addCriterion("DECPOS >", value, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposGreaterThanOrEqualTo(Short value) {
            addCriterion("DECPOS >=", value, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposLessThan(Short value) {
            addCriterion("DECPOS <", value, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposLessThanOrEqualTo(Short value) {
            addCriterion("DECPOS <=", value, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposIn(List<Short> values) {
            addCriterion("DECPOS in", values, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposNotIn(List<Short> values) {
            addCriterion("DECPOS not in", values, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposBetween(Short value1, Short value2) {
            addCriterion("DECPOS between", value1, value2, "decpos");
            return (Criteria) this;
        }

        public Criteria andDecposNotBetween(Short value1, Short value2) {
            addCriterion("DECPOS not between", value1, value2, "decpos");
            return (Criteria) this;
        }

        public Criteria andExcflgIsNull() {
            addCriterion("EXCFLG is null");
            return (Criteria) this;
        }

        public Criteria andExcflgIsNotNull() {
            addCriterion("EXCFLG is not null");
            return (Criteria) this;
        }

        public Criteria andExcflgEqualTo(String value) {
            addCriterion("EXCFLG =", value, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgNotEqualTo(String value) {
            addCriterion("EXCFLG <>", value, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgGreaterThan(String value) {
            addCriterion("EXCFLG >", value, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgGreaterThanOrEqualTo(String value) {
            addCriterion("EXCFLG >=", value, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgLessThan(String value) {
            addCriterion("EXCFLG <", value, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgLessThanOrEqualTo(String value) {
            addCriterion("EXCFLG <=", value, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgLike(String value) {
            addCriterion("EXCFLG like", value, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgNotLike(String value) {
            addCriterion("EXCFLG not like", value, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgIn(List<String> values) {
            addCriterion("EXCFLG in", values, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgNotIn(List<String> values) {
            addCriterion("EXCFLG not in", values, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgBetween(String value1, String value2) {
            addCriterion("EXCFLG between", value1, value2, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcflgNotBetween(String value1, String value2) {
            addCriterion("EXCFLG not between", value1, value2, "excflg");
            return (Criteria) this;
        }

        public Criteria andExcuntIsNull() {
            addCriterion("EXCUNT is null");
            return (Criteria) this;
        }

        public Criteria andExcuntIsNotNull() {
            addCriterion("EXCUNT is not null");
            return (Criteria) this;
        }

        public Criteria andExcuntEqualTo(BigDecimal value) {
            addCriterion("EXCUNT =", value, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntNotEqualTo(BigDecimal value) {
            addCriterion("EXCUNT <>", value, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntGreaterThan(BigDecimal value) {
            addCriterion("EXCUNT >", value, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("EXCUNT >=", value, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntLessThan(BigDecimal value) {
            addCriterion("EXCUNT <", value, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntLessThanOrEqualTo(BigDecimal value) {
            addCriterion("EXCUNT <=", value, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntIn(List<BigDecimal> values) {
            addCriterion("EXCUNT in", values, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntNotIn(List<BigDecimal> values) {
            addCriterion("EXCUNT not in", values, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EXCUNT between", value1, value2, "excunt");
            return (Criteria) this;
        }

        public Criteria andExcuntNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("EXCUNT not between", value1, value2, "excunt");
            return (Criteria) this;
        }

        public Criteria andMinuntIsNull() {
            addCriterion("MINUNT is null");
            return (Criteria) this;
        }

        public Criteria andMinuntIsNotNull() {
            addCriterion("MINUNT is not null");
            return (Criteria) this;
        }

        public Criteria andMinuntEqualTo(BigDecimal value) {
            addCriterion("MINUNT =", value, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntNotEqualTo(BigDecimal value) {
            addCriterion("MINUNT <>", value, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntGreaterThan(BigDecimal value) {
            addCriterion("MINUNT >", value, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("MINUNT >=", value, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntLessThan(BigDecimal value) {
            addCriterion("MINUNT <", value, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntLessThanOrEqualTo(BigDecimal value) {
            addCriterion("MINUNT <=", value, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntIn(List<BigDecimal> values) {
            addCriterion("MINUNT in", values, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntNotIn(List<BigDecimal> values) {
            addCriterion("MINUNT not in", values, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MINUNT between", value1, value2, "minunt");
            return (Criteria) this;
        }

        public Criteria andMinuntNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("MINUNT not between", value1, value2, "minunt");
            return (Criteria) this;
        }

        public Criteria andCutflgIsNull() {
            addCriterion("CUTFLG is null");
            return (Criteria) this;
        }

        public Criteria andCutflgIsNotNull() {
            addCriterion("CUTFLG is not null");
            return (Criteria) this;
        }

        public Criteria andCutflgEqualTo(String value) {
            addCriterion("CUTFLG =", value, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgNotEqualTo(String value) {
            addCriterion("CUTFLG <>", value, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgGreaterThan(String value) {
            addCriterion("CUTFLG >", value, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgGreaterThanOrEqualTo(String value) {
            addCriterion("CUTFLG >=", value, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgLessThan(String value) {
            addCriterion("CUTFLG <", value, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgLessThanOrEqualTo(String value) {
            addCriterion("CUTFLG <=", value, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgLike(String value) {
            addCriterion("CUTFLG like", value, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgNotLike(String value) {
            addCriterion("CUTFLG not like", value, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgIn(List<String> values) {
            addCriterion("CUTFLG in", values, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgNotIn(List<String> values) {
            addCriterion("CUTFLG not in", values, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgBetween(String value1, String value2) {
            addCriterion("CUTFLG between", value1, value2, "cutflg");
            return (Criteria) this;
        }

        public Criteria andCutflgNotBetween(String value1, String value2) {
            addCriterion("CUTFLG not between", value1, value2, "cutflg");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("WEIGHT is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("WEIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(String value) {
            addCriterion("WEIGHT =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(String value) {
            addCriterion("WEIGHT <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(String value) {
            addCriterion("WEIGHT >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(String value) {
            addCriterion("WEIGHT >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(String value) {
            addCriterion("WEIGHT <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(String value) {
            addCriterion("WEIGHT <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLike(String value) {
            addCriterion("WEIGHT like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotLike(String value) {
            addCriterion("WEIGHT not like", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<String> values) {
            addCriterion("WEIGHT in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<String> values) {
            addCriterion("WEIGHT not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(String value1, String value2) {
            addCriterion("WEIGHT between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(String value1, String value2) {
            addCriterion("WEIGHT not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andIntdayIsNull() {
            addCriterion("INTDAY is null");
            return (Criteria) this;
        }

        public Criteria andIntdayIsNotNull() {
            addCriterion("INTDAY is not null");
            return (Criteria) this;
        }

        public Criteria andIntdayEqualTo(String value) {
            addCriterion("INTDAY =", value, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayNotEqualTo(String value) {
            addCriterion("INTDAY <>", value, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayGreaterThan(String value) {
            addCriterion("INTDAY >", value, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayGreaterThanOrEqualTo(String value) {
            addCriterion("INTDAY >=", value, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayLessThan(String value) {
            addCriterion("INTDAY <", value, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayLessThanOrEqualTo(String value) {
            addCriterion("INTDAY <=", value, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayLike(String value) {
            addCriterion("INTDAY like", value, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayNotLike(String value) {
            addCriterion("INTDAY not like", value, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayIn(List<String> values) {
            addCriterion("INTDAY in", values, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayNotIn(List<String> values) {
            addCriterion("INTDAY not in", values, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayBetween(String value1, String value2) {
            addCriterion("INTDAY between", value1, value2, "intday");
            return (Criteria) this;
        }

        public Criteria andIntdayNotBetween(String value1, String value2) {
            addCriterion("INTDAY not between", value1, value2, "intday");
            return (Criteria) this;
        }

        public Criteria andSpeflgIsNull() {
            addCriterion("SPEFLG is null");
            return (Criteria) this;
        }

        public Criteria andSpeflgIsNotNull() {
            addCriterion("SPEFLG is not null");
            return (Criteria) this;
        }

        public Criteria andSpeflgEqualTo(String value) {
            addCriterion("SPEFLG =", value, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgNotEqualTo(String value) {
            addCriterion("SPEFLG <>", value, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgGreaterThan(String value) {
            addCriterion("SPEFLG >", value, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgGreaterThanOrEqualTo(String value) {
            addCriterion("SPEFLG >=", value, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgLessThan(String value) {
            addCriterion("SPEFLG <", value, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgLessThanOrEqualTo(String value) {
            addCriterion("SPEFLG <=", value, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgLike(String value) {
            addCriterion("SPEFLG like", value, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgNotLike(String value) {
            addCriterion("SPEFLG not like", value, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgIn(List<String> values) {
            addCriterion("SPEFLG in", values, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgNotIn(List<String> values) {
            addCriterion("SPEFLG not in", values, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgBetween(String value1, String value2) {
            addCriterion("SPEFLG between", value1, value2, "speflg");
            return (Criteria) this;
        }

        public Criteria andSpeflgNotBetween(String value1, String value2) {
            addCriterion("SPEFLG not between", value1, value2, "speflg");
            return (Criteria) this;
        }

        public Criteria andHolflgIsNull() {
            addCriterion("HOLFLG is null");
            return (Criteria) this;
        }

        public Criteria andHolflgIsNotNull() {
            addCriterion("HOLFLG is not null");
            return (Criteria) this;
        }

        public Criteria andHolflgEqualTo(String value) {
            addCriterion("HOLFLG =", value, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgNotEqualTo(String value) {
            addCriterion("HOLFLG <>", value, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgGreaterThan(String value) {
            addCriterion("HOLFLG >", value, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgGreaterThanOrEqualTo(String value) {
            addCriterion("HOLFLG >=", value, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgLessThan(String value) {
            addCriterion("HOLFLG <", value, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgLessThanOrEqualTo(String value) {
            addCriterion("HOLFLG <=", value, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgLike(String value) {
            addCriterion("HOLFLG like", value, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgNotLike(String value) {
            addCriterion("HOLFLG not like", value, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgIn(List<String> values) {
            addCriterion("HOLFLG in", values, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgNotIn(List<String> values) {
            addCriterion("HOLFLG not in", values, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgBetween(String value1, String value2) {
            addCriterion("HOLFLG between", value1, value2, "holflg");
            return (Criteria) this;
        }

        public Criteria andHolflgNotBetween(String value1, String value2) {
            addCriterion("HOLFLG not between", value1, value2, "holflg");
            return (Criteria) this;
        }

        public Criteria andClrflgIsNull() {
            addCriterion("CLRFLG is null");
            return (Criteria) this;
        }

        public Criteria andClrflgIsNotNull() {
            addCriterion("CLRFLG is not null");
            return (Criteria) this;
        }

        public Criteria andClrflgEqualTo(String value) {
            addCriterion("CLRFLG =", value, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgNotEqualTo(String value) {
            addCriterion("CLRFLG <>", value, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgGreaterThan(String value) {
            addCriterion("CLRFLG >", value, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgGreaterThanOrEqualTo(String value) {
            addCriterion("CLRFLG >=", value, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgLessThan(String value) {
            addCriterion("CLRFLG <", value, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgLessThanOrEqualTo(String value) {
            addCriterion("CLRFLG <=", value, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgLike(String value) {
            addCriterion("CLRFLG like", value, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgNotLike(String value) {
            addCriterion("CLRFLG not like", value, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgIn(List<String> values) {
            addCriterion("CLRFLG in", values, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgNotIn(List<String> values) {
            addCriterion("CLRFLG not in", values, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgBetween(String value1, String value2) {
            addCriterion("CLRFLG between", value1, value2, "clrflg");
            return (Criteria) this;
        }

        public Criteria andClrflgNotBetween(String value1, String value2) {
            addCriterion("CLRFLG not between", value1, value2, "clrflg");
            return (Criteria) this;
        }

        public Criteria andEffdatIsNull() {
            addCriterion("EFFDAT is null");
            return (Criteria) this;
        }

        public Criteria andEffdatIsNotNull() {
            addCriterion("EFFDAT is not null");
            return (Criteria) this;
        }

        public Criteria andEffdatEqualTo(Date value) {
            addCriterion("EFFDAT =", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatNotEqualTo(Date value) {
            addCriterion("EFFDAT <>", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatGreaterThan(Date value) {
            addCriterion("EFFDAT >", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatGreaterThanOrEqualTo(Date value) {
            addCriterion("EFFDAT >=", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatLessThan(Date value) {
            addCriterion("EFFDAT <", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatLessThanOrEqualTo(Date value) {
            addCriterion("EFFDAT <=", value, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatIn(List<Date> values) {
            addCriterion("EFFDAT in", values, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatNotIn(List<Date> values) {
            addCriterion("EFFDAT not in", values, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatBetween(Date value1, Date value2) {
            addCriterion("EFFDAT between", value1, value2, "effdat");
            return (Criteria) this;
        }

        public Criteria andEffdatNotBetween(Date value1, Date value2) {
            addCriterion("EFFDAT not between", value1, value2, "effdat");
            return (Criteria) this;
        }

        public Criteria andExpdatIsNull() {
            addCriterion("EXPDAT is null");
            return (Criteria) this;
        }

        public Criteria andExpdatIsNotNull() {
            addCriterion("EXPDAT is not null");
            return (Criteria) this;
        }

        public Criteria andExpdatEqualTo(Date value) {
            addCriterion("EXPDAT =", value, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatNotEqualTo(Date value) {
            addCriterion("EXPDAT <>", value, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatGreaterThan(Date value) {
            addCriterion("EXPDAT >", value, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatGreaterThanOrEqualTo(Date value) {
            addCriterion("EXPDAT >=", value, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatLessThan(Date value) {
            addCriterion("EXPDAT <", value, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatLessThanOrEqualTo(Date value) {
            addCriterion("EXPDAT <=", value, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatIn(List<Date> values) {
            addCriterion("EXPDAT in", values, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatNotIn(List<Date> values) {
            addCriterion("EXPDAT not in", values, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatBetween(Date value1, Date value2) {
            addCriterion("EXPDAT between", value1, value2, "expdat");
            return (Criteria) this;
        }

        public Criteria andExpdatNotBetween(Date value1, Date value2) {
            addCriterion("EXPDAT not between", value1, value2, "expdat");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIsNull() {
            addCriterion("AMDTLR is null");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIsNotNull() {
            addCriterion("AMDTLR is not null");
            return (Criteria) this;
        }

        public Criteria andAmdtlrEqualTo(String value) {
            addCriterion("AMDTLR =", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotEqualTo(String value) {
            addCriterion("AMDTLR <>", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrGreaterThan(String value) {
            addCriterion("AMDTLR >", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrGreaterThanOrEqualTo(String value) {
            addCriterion("AMDTLR >=", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLessThan(String value) {
            addCriterion("AMDTLR <", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLessThanOrEqualTo(String value) {
            addCriterion("AMDTLR <=", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrLike(String value) {
            addCriterion("AMDTLR like", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotLike(String value) {
            addCriterion("AMDTLR not like", value, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrIn(List<String> values) {
            addCriterion("AMDTLR in", values, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotIn(List<String> values) {
            addCriterion("AMDTLR not in", values, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrBetween(String value1, String value2) {
            addCriterion("AMDTLR between", value1, value2, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andAmdtlrNotBetween(String value1, String value2) {
            addCriterion("AMDTLR not between", value1, value2, "amdtlr");
            return (Criteria) this;
        }

        public Criteria andUpddatIsNull() {
            addCriterion("UPDDAT is null");
            return (Criteria) this;
        }

        public Criteria andUpddatIsNotNull() {
            addCriterion("UPDDAT is not null");
            return (Criteria) this;
        }

        public Criteria andUpddatEqualTo(Date value) {
            addCriterion("UPDDAT =", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotEqualTo(Date value) {
            addCriterion("UPDDAT <>", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatGreaterThan(Date value) {
            addCriterion("UPDDAT >", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatGreaterThanOrEqualTo(Date value) {
            addCriterion("UPDDAT >=", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatLessThan(Date value) {
            addCriterion("UPDDAT <", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatLessThanOrEqualTo(Date value) {
            addCriterion("UPDDAT <=", value, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatIn(List<Date> values) {
            addCriterion("UPDDAT in", values, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotIn(List<Date> values) {
            addCriterion("UPDDAT not in", values, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatBetween(Date value1, Date value2) {
            addCriterion("UPDDAT between", value1, value2, "upddat");
            return (Criteria) this;
        }

        public Criteria andUpddatNotBetween(Date value1, Date value2) {
            addCriterion("UPDDAT not between", value1, value2, "upddat");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNull() {
            addCriterion("RECSTS is null");
            return (Criteria) this;
        }

        public Criteria andRecstsIsNotNull() {
            addCriterion("RECSTS is not null");
            return (Criteria) this;
        }

        public Criteria andRecstsEqualTo(String value) {
            addCriterion("RECSTS =", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotEqualTo(String value) {
            addCriterion("RECSTS <>", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThan(String value) {
            addCriterion("RECSTS >", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsGreaterThanOrEqualTo(String value) {
            addCriterion("RECSTS >=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThan(String value) {
            addCriterion("RECSTS <", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLessThanOrEqualTo(String value) {
            addCriterion("RECSTS <=", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsLike(String value) {
            addCriterion("RECSTS like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotLike(String value) {
            addCriterion("RECSTS not like", value, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsIn(List<String> values) {
            addCriterion("RECSTS in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotIn(List<String> values) {
            addCriterion("RECSTS not in", values, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsBetween(String value1, String value2) {
            addCriterion("RECSTS between", value1, value2, "recsts");
            return (Criteria) this;
        }

        public Criteria andRecstsNotBetween(String value1, String value2) {
            addCriterion("RECSTS not between", value1, value2, "recsts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 09 20:06:45 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SBS_ACTCCY
     *
     * @mbggenerated Sat Apr 09 20:06:45 CST 2011
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}